/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import * as DomeApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Ai {
    export interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Ai {
    constructor(protected readonly _options: Ai.Options) {}

    /**
     * @param {DomeApi.ReprocessBody} request
     * @param {Ai.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link DomeApi.BadRequestError}
     * @throws {@link DomeApi.UnauthorizedError}
     * @throws {@link DomeApi.NotFoundError}
     * @throws {@link DomeApi.InternalServerError}
     *
     * @example
     *     await client.ai.reprocessAiMetadata({
     *         contentId: "content_abc123"
     *     })
     */
    public reprocessAiMetadata(
        request: DomeApi.ReprocessBody,
        requestOptions?: Ai.RequestOptions,
    ): core.HttpResponsePromise<DomeApi.ReprocessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__reprocessAiMetadata(request, requestOptions));
    }

    private async __reprocessAiMetadata(
        request: DomeApi.ReprocessBody,
        requestOptions?: Ai.RequestOptions,
    ): Promise<core.WithRawResponse<DomeApi.ReprocessResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "ai/reprocess",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.ReprocessBody.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ReprocessResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new DomeApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new DomeApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new DomeApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new DomeApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.DomeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DomeApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DomeApiTimeoutError("Timeout exceeded when calling POST /ai/reprocess.");
            case "unknown":
                throw new errors.DomeApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {DomeApi.BulkReprocessBody} request
     * @param {Ai.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link DomeApi.BadRequestError}
     * @throws {@link DomeApi.UnauthorizedError}
     * @throws {@link DomeApi.InternalServerError}
     *
     * @example
     *     await client.ai.bulkReprocessAiMetadata({
     *         contentIds: ["contentIds"]
     *     })
     */
    public bulkReprocessAiMetadata(
        request: DomeApi.BulkReprocessBody,
        requestOptions?: Ai.RequestOptions,
    ): core.HttpResponsePromise<DomeApi.BulkReprocessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__bulkReprocessAiMetadata(request, requestOptions));
    }

    private async __bulkReprocessAiMetadata(
        request: DomeApi.BulkReprocessBody,
        requestOptions?: Ai.RequestOptions,
    ): Promise<core.WithRawResponse<DomeApi.BulkReprocessResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "ai/bulk-reprocess",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.BulkReprocessBody.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.BulkReprocessResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new DomeApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new DomeApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new DomeApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.DomeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DomeApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DomeApiTimeoutError("Timeout exceeded when calling POST /ai/bulk-reprocess.");
            case "unknown":
                throw new errors.DomeApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
