/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         code: "auth_code_from_notion"
 *     }
 */
export interface StoreNotionIntegrationBody {
    code: string;
    state?: string;
}
