name = "auth"
main = "src/index.ts"
account_id = "d566e3c491e1cef6c530d45b76672814"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

[vars]
ENVIRONMENT = "development"
VERSION = "0.1.0"

# Dev environment variables
[dev.vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "auth-db"
database_id = "69a22f1e-a230-4b1a-8bdf-db0c7beb1502"

# KV namespace for storing tokens (optional blacklisted tokens)
[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "152a516f80b54b17a4f458dddb896fcf"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
