/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index";
import * as DomeApi from "../index";
export declare class ConflictError extends errors.DomeApiError {
    constructor(body: DomeApi.ErrorResponse);
}
