name = "silo"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "silo-content"

[[d1_databases]]
binding = "DB"
database_name = "silo"
database_id = "baf652ea-e575-4019-b95c-c9d44d02c1aa"

[[queues.producers]]
binding = "NEW_CONTENT_CONSTELLATION"
queue = "new-content-constellation"

[[queues.producers]]
binding = "NEW_CONTENT_AI"
queue = "new-content-ai"

[[queues.consumers]]
binding = "CONTENT_EVENTS"
queue = "content-events"

[[queues.consumers]]
binding = "ENRICHED_CONTENT"
queue = "enriched-content"

[vars]
LOG_LEVEL = "info"
VERSION = "1.0.0"
ENVIRONMENT = "prod"

# Development environment variables
[env.dev]
name = "silo-dev"
[env.dev.vars]
LOG_LEVEL = "debug"
ENVIRONMENT = "dev"

# Staging environment variables
[env.staging]
name = "silo-staging"
[env.staging.vars]
LOG_LEVEL = "info"
ENVIRONMENT = "staging"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
