name = "silo"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "silo-content"

[[d1_databases]]
binding = "DB"
database_name = "silo"
database_id = "9d6e9f55-05c6-4181-aa4d-0d7a3477396d"

[[queues.producers]]
binding = "NEW_CONTENT_CONSTELLATION"
queue = "new-content-constellation"

[[queues.producers]]
binding = "NEW_CONTENT_AI"
queue = "new-content-ai"

[[queues.producers]]
binding = "INGEST_DLQ"
queue = "ingest-dlq"

[[queues.producers]]
binding = "INGEST_QUEUE"
queue = "ingest-queue"

[[queues.consumers]]
queue = "content-events"

[[queues.consumers]]
queue = "enriched-content"

[[queues.consumers]]
queue = "ingest-queue"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = "ingest-dead-letter"

[[queues.consumers]]
queue = "ingest-dead-letter"
max_batch_size = 5
max_batch_timeout = 10

[vars]
LOG_LEVEL = "info"
VERSION = "1.0.0"
ENVIRONMENT = "prod"

# Development environment variables
[env.dev]
name = "silo-dev"
[env.dev.vars]
LOG_LEVEL = "debug"
ENVIRONMENT = "dev"

# Staging environment variables
[env.staging]
name = "silo-staging"
[env.staging.vars]
LOG_LEVEL = "info"
ENVIRONMENT = "staging"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
