/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         contentIds: ["contentIds"]
 *     }
 */
export interface BulkReprocessBody {
    contentIds: string[];
}
