/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         contentId: "content_abc123"
 *     }
 */
export interface ReprocessBody {
    contentId: string;
}
