/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostChatRequestMessagesItemRole } from "./PostChatRequestMessagesItemRole";
export declare const PostChatRequestMessagesItem: core.serialization.ObjectSchema<serializers.PostChatRequestMessagesItem.Raw, DomeApi.PostChatRequestMessagesItem>;
export declare namespace PostChatRequestMessagesItem {
    interface Raw {
        role: PostChatRequestMessagesItemRole.Raw;
        content: string;
        timestamp?: number | null;
    }
}
