/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const PostChatRequestOptions: core.serialization.ObjectSchema<serializers.PostChatRequestOptions.Raw, DomeApi.PostChatRequestOptions>;
export declare namespace PostChatRequestOptions {
    interface Raw {
        enhanceWithContext?: boolean | null;
        maxContextItems?: number | null;
        includeSourceInfo?: boolean | null;
        maxTokens?: number | null;
        temperature?: number | null;
        modelId?: string | null;
    }
}
