/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ConfigureNotionOAuthBody: core.serialization.Schema<
    serializers.ConfigureNotionOAuthBody.Raw,
    DomeApi.ConfigureNotionOAuthBody
> = core.serialization.object({
    clientId: core.serialization.string().optional(),
    clientSecret: core.serialization.string().optional(),
    redirectUri: core.serialization.string().optional(),
});

export declare namespace ConfigureNotionOAuthBody {
    export interface Raw {
        clientId?: string | null;
        clientSecret?: string | null;
        redirectUri?: string | null;
    }
}
