/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const StoreNotionIntegrationBody: core.serialization.Schema<
    serializers.StoreNotionIntegrationBody.Raw,
    DomeApi.StoreNotionIntegrationBody
> = core.serialization.object({
    code: core.serialization.string(),
    state: core.serialization.string().optional(),
});

export declare namespace StoreNotionIntegrationBody {
    export interface Raw {
        code: string;
        state?: string | null;
    }
}
