name = "{{SERVICE_NAME}}"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[env.dev]
name = "{{SERVICE_NAME}}-dev"

[env.staging]
name = "{{SERVICE_NAME}}-staging"

[env.prod]
name = "{{SERVICE_NAME}}-prod"

# Example bindings - update as needed
# [[env.dev.d1_databases]]
# binding = "DB"
# database_name = "{{SERVICE_NAME}}-dev-db"
# database_id = "your-database-id"

# [[env.dev.vectorize]]
# binding = "VECTORIZE"
# index_name = "{{SERVICE_NAME}}-dev-index"

# [[env.dev.queues]]
# binding = "EXAMPLE_QUEUE"
# queue = "{{SERVICE_NAME}}-dev-queue"

# [[env.dev.services]]
# binding = "AUTH"
# service = "auth-dev"

# [env.dev.vars]
# ENVIRONMENT = "development"
# LOG_LEVEL = "debug"