/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as DomeApi from "../../../index";
export declare namespace Public {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Public {
    protected readonly _options: Public.Options;
    constructor(_options: Public.Options);
    /**
     * Provides basic information about the API service.
     *
     * @param {Public.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.public.apiRoot()
     */
    apiRoot(requestOptions?: Public.RequestOptions): Promise<DomeApi.RootResponse>;
    /**
     * Checks the health status of the API service.
     *
     * @param {Public.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.public.healthCheck()
     */
    healthCheck(requestOptions?: Public.RequestOptions): Promise<DomeApi.HealthResponse>;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
