# wrangler.shared.toml - only bindings, zero Worker-specific keys
[[d1_databases]]
binding = "D1_DATABASE"
database_name = "dome-meta"
database_id = "ac198406-1036-495e-b0f1-b61f7c9ecbdf"
preview_database_id = "672837d0-28fc-4ac8-9144-86653a2d0965"
migrations_dir = "services/dome-api/migrations"   # mono-repo friendly

[[vectorize]]
binding = "VECTORIZE"
index_name = "dome-notes"         # removed index_id as Wrangler ignores it

[[r2_buckets]]
binding = "RAW"
bucket_name = "dome-raw"
preview_bucket_name = "dome-raw-dev"

[[queues.producers]]
binding = "EVENTS"
queue = "dome-events"