/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { IngestNoteBodyApiSchemaCategory } from "../../types/IngestNoteBodyApiSchemaCategory";
import { IngestNoteBodyApiSchemaMimeType } from "../../types/IngestNoteBodyApiSchemaMimeType";

export const IngestNoteBodyApiSchema: core.serialization.Schema<
    serializers.IngestNoteBodyApiSchema.Raw,
    DomeApi.IngestNoteBodyApiSchema
> = core.serialization.object({
    title: core.serialization.string().optional(),
    content: core.serialization.string(),
    category: IngestNoteBodyApiSchemaCategory.optional(),
    mimeType: IngestNoteBodyApiSchemaMimeType.optional(),
});

export declare namespace IngestNoteBodyApiSchema {
    export interface Raw {
        title?: string | null;
        content: string;
        category?: IngestNoteBodyApiSchemaCategory.Raw | null;
        mimeType?: IngestNoteBodyApiSchemaMimeType.Raw | null;
    }
}
