/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         email: "mark@example.com",
 *         password: "hunter2"
 *     }
 */
export interface LoginBody {
    /** User's email address */
    email: string;
    /** User's password (min 8 characters) */
    password: string;
}
