/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         refreshToken: "ey..."
 *     }
 */
export interface RefreshBody {
    /** Valid refresh token */
    refreshToken: string;
}
