/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         email: "newuser@example.com",
 *         password: "securepassword123",
 *         name: "New User"
 *     }
 */
export interface RegisterBody {
    /** New user's email address */
    email: string;
    /** New user's password (min 8 characters) */
    password: string;
    /** New user's full name */
    name: string;
}
