/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const LoginBody: core.serialization.Schema<serializers.LoginBody.Raw, DomeApi.LoginBody> =
    core.serialization.object({
        email: core.serialization.string(),
        password: core.serialization.string(),
    });

export declare namespace LoginBody {
    export interface Raw {
        email: string;
        password: string;
    }
}
