/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const RefreshBody: core.serialization.Schema<serializers.RefreshBody.Raw, DomeApi.RefreshBody> =
    core.serialization.object({
        refreshToken: core.serialization.string(),
    });

export declare namespace RefreshBody {
    export interface Raw {
        refreshToken: string;
    }
}
