/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const RegisterBody: core.serialization.Schema<serializers.RegisterBody.Raw, DomeApi.RegisterBody> =
    core.serialization.object({
        email: core.serialization.string(),
        password: core.serialization.string(),
        name: core.serialization.string(),
    });

export declare namespace RegisterBody {
    export interface Raw {
        email: string;
        password: string;
        name: string;
    }
}
