name = "auth-telegram"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
TELEGRAM_API_ID = ""
TELEGRAM_API_HASH = ""
SESSION_SECRET = ""
API_KEY = ""
ADMIN_API_KEY = ""

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "auth_telegram_db"
database_id = "placeholder-id" # This will be replaced during deployment

# For local development
[dev]
port = 8788

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }

# Staging environment
[env.staging]
vars = { ENVIRONMENT = "staging" }
