/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const RegisterGithubRepoBody: core.serialization.Schema<serializers.RegisterGithubRepoBody.Raw, DomeApi.RegisterGithubRepoBody>;
export declare namespace RegisterGithubRepoBody {
    interface Raw {
        owner: string;
        repo: string;
    }
}
