name = "chat-orchestrator"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

# D1 database for checkpointing
[[d1_databases]]
binding = "CHAT_DB"
database_name = "chat_orchestrator"
database_id = "placeholder-id" # This will be replaced during deployment

# Service bindings
[[services]]
binding = "CONSTELLATION"
service = "constellation"

[[services]]
binding = "SILO"
service = "silo"

# For local development
[dev]
port = 8788

[vars]
VERSION = "0.1.0"
LOG_LEVEL = "debug"
ENCRYPTION_KEY = "replace_me"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
command = "pnpm build"

[observability]
enabled = true
head_sampling_rate = 1
