/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         q: "q"
 *     }
 */
export interface GetSearchRequest {
    q: string;
    limit?: number;
    offset?: number;
    category?: string;
    mimeType?: string;
    startDate?: number;
    endDate?: number;
    useCache?: boolean;
}
