/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         token: "jwt_token_here"
 *     }
 */
export interface GetChatWsRequest {
    token?: string;
}
