/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../../../../index";

/**
 * @example
 *     {
 *         userId: "userId",
 *         messages: [{
 *                 role: "user",
 *                 content: "content"
 *             }],
 *         options: {}
 *     }
 */
export interface PostChatRequest {
    stream?: boolean;
    userId: string;
    messages: DomeApi.PostChatRequestMessagesItem[];
    options: DomeApi.PostChatRequestOptions;
    runId?: string;
}
