name = "push-message-ingestor"
main = "src/index.ts"
compatibility_date = "2023-04-15"

# Queue bindings
[[queues.producers]]
queue = "rawmessages"
binding = "RAW_MESSAGES_QUEUE"

[vars]
ENVIRONMENT = "development"

# For local development
[dev]
port = 8787
# For local development
[dev.vars]
ENVIRONMENT = "development"
binding = "RAW_MESSAGES_QUEUE"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
command = "pnpm build"
