"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetNotesRequestCategory = void 0;
exports.GetNotesRequestCategory = {
    Note: "note",
    Code: "code",
    Document: "document",
    Article: "article",
    Other: "other",
};
