name = "tsunami"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

## D1 database for `sync_plan` table
[[d1_databases]]
binding        = "SYNC_PLAN"
database_name  = "sync-plan"
database_id = "3809336f-4cf7-41d3-8959-0930c2d2634e"
migrations_dir = "migrations"

[[services]]
binding = "SILO"
service = "silo"
environment = "production"

# Durable Object for resource sync
[[durable_objects.bindings]]
name = "RESOURCE_OBJECT"
class_name = "ResourceObject"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["ResourceObject"] # Array of new classes

# Queue producers
[[queues.producers]]
queue = "silo-ingest-queue"
binding = "SILO_INGEST_QUEUE"

#################################################################
# Secrets / runtime constants
#################################################################

[vars]
LOG_LEVEL = "info"
VERSION = "1.0.0"
ENVIRONMENT = "prod"
# GITHUB_TOKEN = "" # Optional for public repos, but recommended to avoid rate limits
# To set: wrangler secret put GITHUB_TOKEN


[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
