name = "tsunami"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

## D1 database for `sync_plan` table
[[d1_databases]]
binding        = "SYNC_PLAN"
database_name  = "sync-plan"
database_id = "3130eb73-702f-4f87-ac5f-97e970dd8342"

[[services]]
binding = "SILO"
service = "silo"
environment = "production"

# Durable Object for resource sync
[[durable_objects.bindings]]
name = "RESOURCE_OBJECT"
class_name = "ResourceObject"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["ResourceObject"] # Array of new classes

#################################################################
# Triggers
#################################################################

[triggers]
# Poll external sources every 15 minutes
crons = ["*/15 * * * *"]

#################################################################
# Secrets / runtime constants
#################################################################

[vars]
LOG_LEVEL = "info"
VERSION = "1.0.0"
ENVIRONMENT = "prod"
# GITHUB_TOKEN = "" # Uncomment and set this in production or use wrangler secrets
