/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { BadRequestErrorBodyError } from "./BadRequestErrorBodyError";
export declare const BadRequestErrorBody: core.serialization.ObjectSchema<serializers.BadRequestErrorBody.Raw, DomeApi.BadRequestErrorBody>;
export declare namespace BadRequestErrorBody {
    interface Raw {
        success?: boolean | null;
        error?: BadRequestErrorBodyError.Raw | null;
    }
}
