/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { ChatErrorResponseError } from "./ChatErrorResponseError";
export declare const ChatErrorResponse: core.serialization.ObjectSchema<serializers.ChatErrorResponse.Raw, DomeApi.ChatErrorResponse>;
export declare namespace ChatErrorResponse {
    interface Raw {
        success: boolean;
        error: ChatErrorResponseError.Raw;
    }
}
