/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const ErrorResponseError: core.serialization.ObjectSchema<serializers.ErrorResponseError.Raw, DomeApi.ErrorResponseError>;
export declare namespace ErrorResponseError {
    interface Raw {
        code: string;
        message: string;
    }
}
