/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { ForbiddenErrorBodyError } from "./ForbiddenErrorBodyError";
export declare const ForbiddenErrorBody: core.serialization.ObjectSchema<serializers.ForbiddenErrorBody.Raw, DomeApi.ForbiddenErrorBody>;
export declare namespace ForbiddenErrorBody {
    interface Raw {
        success?: boolean | null;
        error?: ForbiddenErrorBodyError.Raw | null;
    }
}
