/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { HealthResponseMetrics } from "./HealthResponseMetrics";
export declare const HealthResponse: core.serialization.ObjectSchema<serializers.HealthResponse.Raw, DomeApi.HealthResponse>;
export declare namespace HealthResponse {
    interface Raw {
        status: "ok";
        timestamp: string;
        service: string;
        version: string;
        metrics?: HealthResponseMetrics.Raw | null;
    }
}
