/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { HealthResponseMetricsCounters } from "./HealthResponseMetricsCounters";
export declare const HealthResponseMetrics: core.serialization.ObjectSchema<serializers.HealthResponseMetrics.Raw, DomeApi.HealthResponseMetrics>;
export declare namespace HealthResponseMetrics {
    interface Raw {
        counters: HealthResponseMetricsCounters.Raw;
    }
}
