/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const HealthResponseMetricsCounters: core.serialization.ObjectSchema<serializers.HealthResponseMetricsCounters.Raw, DomeApi.HealthResponseMetricsCounters>;
export declare namespace HealthResponseMetricsCounters {
    interface Raw {
        requests?: number | null;
        errors?: number | null;
    }
}
