/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const InternalServerErrorBodyError: core.serialization.ObjectSchema<serializers.InternalServerErrorBodyError.Raw, DomeApi.InternalServerErrorBodyError>;
export declare namespace InternalServerErrorBodyError {
    interface Raw {
        code: string;
        message: string;
    }
}
