/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const NoteMimeType: core.serialization.Schema<serializers.NoteMimeType.Raw, DomeApi.NoteMimeType>;
export declare namespace NoteMimeType {
    type Raw = "text/plain" | "text/markdown" | "text/html" | "application/json" | "application/javascript" | "application/python" | "application/pdf" | "image/jpeg" | "image/png" | string;
}
