/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const NoteCategory: core.serialization.Schema<serializers.NoteCategory.Raw, DomeApi.NoteCategory>;
export declare namespace NoteCategory {
    type Raw = "note" | "code" | "document" | "article" | "other";
}
