/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const NotionSyncHistoryItem: core.serialization.ObjectSchema<serializers.NotionSyncHistoryItem.Raw, DomeApi.NotionSyncHistoryItem>;
export declare namespace NotionSyncHistoryItem {
    interface Raw {
        id: string;
        timestamp: string;
        status: string;
        details?: string | null;
    }
}
