/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const RegisterResponse: core.serialization.ObjectSchema<serializers.RegisterResponse.Raw, DomeApi.RegisterResponse>;
export declare namespace RegisterResponse {
    interface Raw {
        token: string;
    }
}
