/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { RootResponseService } from "./RootResponseService";
export declare const RootResponse: core.serialization.ObjectSchema<serializers.RootResponse.Raw, DomeApi.RootResponse>;
export declare namespace RootResponse {
    interface Raw {
        message: string;
        service: RootResponseService.Raw;
        description: string;
    }
}
