/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { SearchResultItem } from "./SearchResultItem";
import { Pagination } from "./Pagination";
export declare const SearchResponse: core.serialization.ObjectSchema<serializers.SearchResponse.Raw, DomeApi.SearchResponse>;
export declare namespace SearchResponse {
    interface Raw {
        success: boolean;
        results: SearchResultItem.Raw[];
        pagination: Pagination.Raw;
        query: string;
        message?: string | null;
    }
}
