/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { SearchErrorResponseError } from "./SearchErrorResponseError";
export declare const SearchErrorResponse: core.serialization.ObjectSchema<serializers.SearchErrorResponse.Raw, DomeApi.SearchErrorResponse>;
export declare namespace SearchErrorResponse {
    interface Raw {
        success: boolean;
        error: SearchErrorResponseError.Raw;
    }
}
