/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { StreamingMetadata } from "./StreamingMetadata";
import { StreamingResultData } from "./StreamingResultData";
import { StreamingErrorData } from "./StreamingErrorData";
export declare const StreamingSearchEvent: core.serialization.Schema<serializers.StreamingSearchEvent.Raw, DomeApi.StreamingSearchEvent>;
export declare namespace StreamingSearchEvent {
    type Raw = StreamingSearchEvent.Metadata | StreamingSearchEvent.Result | StreamingSearchEvent.Error;
    interface Metadata extends StreamingMetadata.Raw {
        type: "metadata";
    }
    interface Result extends StreamingResultData.Raw {
        type: "result";
    }
    interface Error extends StreamingErrorData.Raw {
        type: "error";
    }
}
