/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { SyncHistoryItem } from "./SyncHistoryItem";
export declare const SyncHistoryResponse: core.serialization.Schema<serializers.SyncHistoryResponse.Raw, DomeApi.SyncHistoryResponse>;
export declare namespace SyncHistoryResponse {
    type Raw = SyncHistoryItem.Raw[];
}
