/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const UnauthorizedErrorBodyError: core.serialization.ObjectSchema<serializers.UnauthorizedErrorBodyError.Raw, DomeApi.UnauthorizedErrorBodyError>;
export declare namespace UnauthorizedErrorBodyError {
    interface Raw {
        code: string;
        message: string;
    }
}
