/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Defaults to 'note' if not provided
 */
export type IngestNoteBodyApiSchemaCategory = "note" | "code" | "document" | "article" | "other";
export const IngestNoteBodyApiSchemaCategory = {
    Note: "note",
    Code: "code",
    Document: "document",
    Article: "article",
    Other: "other",
} as const;
