/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Defaults to 'text/markdown' if not provided
 */
export type IngestNoteBodyApiSchemaMimeType =
    | "text/plain"
    | "text/markdown"
    | "text/html"
    | "application/json"
    | "application/javascript"
    | "application/python"
    | "application/pdf"
    | "image/jpeg"
    | "image/png"
    | string;
