// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	ENVIRONMENT: "development";
	VERSION: "0.1.0";
	RAW: R2Bucket;
	D1_DATABASE: D1Database;
	EVENTS: Queue;
	VECTORIZE: VectorizeIndex;
}
