name = "dome-api"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "dome-meta"
database_id = "ac198406-1036-495e-b0f1-b61f7c9ecbdf"
preview_database_id = "672837d0-28fc-4ac8-9144-86653a2d0965"
migrations_dir = "services/dome-api/migrations"   # mono-repo friendly

[[r2_buckets]]
binding = "RAW"
bucket_name = "dome-raw"
preview_bucket_name = "dome-raw-dev"

[[queues.producers]]
binding = "EVENTS"
queue = "dome-events"

# Add queue producer for embedding jobs
[[queues.producers]]
binding = "EMBED_QUEUE"
queue = "embed-queue"

# Workers AI binding
[ai]
binding = "AI"

# Constellation service binding
[[services]]
binding = "CONSTELLATION"
service = "constellation"
environment = "production"

# For local development
[dev]
port = 8787

[vars]
VERSION = "0.1.0"
LOG_LEVEL = "debug"

[env.production]
vars = { ENVIRONMENT = "production" }

# Production-specific service binding
[[env.production.services]]
binding = "CONSTELLATION"
service = "constellation"
environment = "production"

[env.staging]
vars = { ENVIRONMENT = "staging" }
command = "pnpm build"

# Staging-specific service binding
[[env.staging.services]]
binding = "CONSTELLATION"
service = "constellation"
environment = "staging"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
