/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const BadRequestErrorBodyError: core.serialization.ObjectSchema<serializers.BadRequestErrorBodyError.Raw, DomeApi.BadRequestErrorBodyError>;
export declare namespace BadRequestErrorBodyError {
    interface Raw {
        code: string;
        message: string;
    }
}
