/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const BulkReprocessResponse: core.serialization.ObjectSchema<
    serializers.BulkReprocessResponse.Raw,
    DomeApi.BulkReprocessResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    reprocessedCount: core.serialization.number().optional(),
});

export declare namespace BulkReprocessResponse {
    export interface Raw {
        success: boolean;
        message: string;
        reprocessedCount?: number | null;
    }
}
