/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const BulkReprocessResponse: core.serialization.ObjectSchema<serializers.BulkReprocessResponse.Raw, DomeApi.BulkReprocessResponse>;
export declare namespace BulkReprocessResponse {
    interface Raw {
        success: boolean;
        message: string;
        reprocessedCount?: number | null;
    }
}
