/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { ChatSource } from "./ChatSource";
export declare const ChatSuccessData: core.serialization.ObjectSchema<serializers.ChatSuccessData.Raw, DomeApi.ChatSuccessData>;
export declare namespace ChatSuccessData {
    interface Raw {
        response: string;
        sources?: ChatSource.Raw[] | null;
    }
}
