/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const ChatErrorResponseError: core.serialization.ObjectSchema<serializers.ChatErrorResponseError.Raw, DomeApi.ChatErrorResponseError>;
export declare namespace ChatErrorResponseError {
    interface Raw {
        code: string;
        message: string;
    }
}
