/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const ChatSource: core.serialization.ObjectSchema<serializers.ChatSource.Raw, DomeApi.ChatSource>;
export declare namespace ChatSource {
    interface Raw {
        id: string;
        type: string;
        title?: string | null;
        url?: string | null;
    }
}
