/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { ChatSource } from "./ChatSource";

export const ChatSuccessData: core.serialization.ObjectSchema<
    serializers.ChatSuccessData.Raw,
    DomeApi.ChatSuccessData
> = core.serialization.object({
    response: core.serialization.string(),
    sources: core.serialization.list(ChatSource).optional(),
});

export declare namespace ChatSuccessData {
    export interface Raw {
        response: string;
        sources?: ChatSource.Raw[] | null;
    }
}
