/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const DeleteSuccessResponse: core.serialization.ObjectSchema<serializers.DeleteSuccessResponse.Raw, DomeApi.DeleteSuccessResponse>;
export declare namespace DeleteSuccessResponse {
    interface Raw {
        success: boolean;
        message: string;
    }
}
