/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { ErrorResponseError } from "./ErrorResponseError";
export declare const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, DomeApi.ErrorResponse>;
export declare namespace ErrorResponse {
    interface Raw {
        success: boolean;
        error: ErrorResponseError.Raw;
    }
}
