/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const ForbiddenErrorBodyError: core.serialization.ObjectSchema<serializers.ForbiddenErrorBodyError.Raw, DomeApi.ForbiddenErrorBodyError>;
export declare namespace ForbiddenErrorBodyError {
    interface Raw {
        code: string;
        message: string;
    }
}
