/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { ForbiddenErrorBodyError } from "./ForbiddenErrorBodyError";

export const ForbiddenErrorBody: core.serialization.ObjectSchema<
    serializers.ForbiddenErrorBody.Raw,
    DomeApi.ForbiddenErrorBody
> = core.serialization.object({
    success: core.serialization.boolean().optional(),
    error: ForbiddenErrorBodyError.optional(),
});

export declare namespace ForbiddenErrorBody {
    export interface Raw {
        success?: boolean | null;
        error?: ForbiddenErrorBodyError.Raw | null;
    }
}
