/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const GithubRepoResponse: core.serialization.ObjectSchema<serializers.GithubRepoResponse.Raw, DomeApi.GithubRepoResponse>;
export declare namespace GithubRepoResponse {
    interface Raw {
        id: string;
        owner: string;
        name: string;
    }
}
