/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const HealthResponseMetricsCounters: core.serialization.ObjectSchema<
    serializers.HealthResponseMetricsCounters.Raw,
    DomeApi.HealthResponseMetricsCounters
> = core.serialization.object({
    requests: core.serialization.number().optional(),
    errors: core.serialization.number().optional(),
});

export declare namespace HealthResponseMetricsCounters {
    export interface Raw {
        requests?: number | null;
        errors?: number | null;
    }
}
