/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { HealthResponseMetrics } from "./HealthResponseMetrics";

export const HealthResponse: core.serialization.ObjectSchema<serializers.HealthResponse.Raw, DomeApi.HealthResponse> =
    core.serialization.object({
        status: core.serialization.stringLiteral("ok"),
        timestamp: core.serialization.date(),
        service: core.serialization.string(),
        version: core.serialization.string(),
        metrics: HealthResponseMetrics.optional(),
    });

export declare namespace HealthResponse {
    export interface Raw {
        status: "ok";
        timestamp: string;
        service: string;
        version: string;
        metrics?: HealthResponseMetrics.Raw | null;
    }
}
