/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const LogoutResponse: core.serialization.ObjectSchema<serializers.LogoutResponse.Raw, DomeApi.LogoutResponse>;
export declare namespace LogoutResponse {
    interface Raw {
        success: boolean;
        message: string;
    }
}
