/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const LogoutResponse: core.serialization.ObjectSchema<serializers.LogoutResponse.Raw, DomeApi.LogoutResponse> =
    core.serialization.object({
        success: core.serialization.boolean(),
        message: core.serialization.string(),
    });

export declare namespace LogoutResponse {
    export interface Raw {
        success: boolean;
        message: string;
    }
}
