/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { NoteCategory } from "./NoteCategory";
import { NoteMimeType } from "./NoteMimeType";
export declare const Note: core.serialization.ObjectSchema<serializers.Note.Raw, DomeApi.Note>;
export declare namespace Note {
    interface Raw {
        id: string;
        userId?: string | null;
        category: NoteCategory.Raw;
        title?: string | null;
        content?: string | null;
        mimeType: NoteMimeType.Raw;
        size: number;
        createdAt: string;
        url?: string | null;
        customMetadata?: Record<string, unknown> | null;
    }
}
