/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const NoteMimeType: core.serialization.Schema<serializers.NoteMimeType.Raw, DomeApi.NoteMimeType> =
    core.serialization.undiscriminatedUnion([
        core.serialization.stringLiteral("text/plain"),
        core.serialization.stringLiteral("text/markdown"),
        core.serialization.stringLiteral("text/html"),
        core.serialization.stringLiteral("application/json"),
        core.serialization.stringLiteral("application/javascript"),
        core.serialization.stringLiteral("application/python"),
        core.serialization.stringLiteral("application/pdf"),
        core.serialization.stringLiteral("image/jpeg"),
        core.serialization.stringLiteral("image/png"),
        core.serialization.string(),
    ]);

export declare namespace NoteMimeType {
    export type Raw =
        | "text/plain"
        | "text/markdown"
        | "text/html"
        | "application/json"
        | "application/javascript"
        | "application/python"
        | "application/pdf"
        | "image/jpeg"
        | "image/png"
        | string;
}
