/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { NotFoundErrorBodyError } from "./NotFoundErrorBodyError";
export declare const NotFoundErrorBody: core.serialization.ObjectSchema<serializers.NotFoundErrorBody.Raw, DomeApi.NotFoundErrorBody>;
export declare namespace NotFoundErrorBody {
    interface Raw {
        success?: boolean | null;
        error?: NotFoundErrorBodyError.Raw | null;
    }
}
