/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const NotFoundErrorBodyError: core.serialization.ObjectSchema<serializers.NotFoundErrorBodyError.Raw, DomeApi.NotFoundErrorBodyError>;
export declare namespace NotFoundErrorBodyError {
    interface Raw {
        code: string;
        message: string;
    }
}
