/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { NotionSyncHistoryItem } from "./NotionSyncHistoryItem";
export declare const NotionSyncHistoryResponse: core.serialization.Schema<serializers.NotionSyncHistoryResponse.Raw, DomeApi.NotionSyncHistoryResponse>;
export declare namespace NotionSyncHistoryResponse {
    type Raw = NotionSyncHistoryItem.Raw[];
}
