/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const NotionGenericSuccessResponse: core.serialization.ObjectSchema<serializers.NotionGenericSuccessResponse.Raw, DomeApi.NotionGenericSuccessResponse>;
export declare namespace NotionGenericSuccessResponse {
    interface Raw {
        success: boolean;
        message?: string | null;
    }
}
