/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { NotionErrorResponseError } from "./NotionErrorResponseError";

export const NotionErrorResponse: core.serialization.ObjectSchema<
    serializers.NotionErrorResponse.Raw,
    DomeApi.NotionErrorResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    error: NotionErrorResponseError,
});

export declare namespace NotionErrorResponse {
    export interface Raw {
        success: boolean;
        error: NotionErrorResponseError.Raw;
    }
}
