/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const NotionWorkspaceResponse: core.serialization.ObjectSchema<serializers.NotionWorkspaceResponse.Raw, DomeApi.NotionWorkspaceResponse>;
export declare namespace NotionWorkspaceResponse {
    interface Raw {
        id: string;
        name: string;
    }
}
