/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const NotionErrorResponseError: core.serialization.ObjectSchema<serializers.NotionErrorResponseError.Raw, DomeApi.NotionErrorResponseError>;
export declare namespace NotionErrorResponseError {
    interface Raw {
        code: string;
        message: string;
    }
}
