/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const NotionSyncHistoryItem: core.serialization.ObjectSchema<
    serializers.NotionSyncHistoryItem.Raw,
    DomeApi.NotionSyncHistoryItem
> = core.serialization.object({
    id: core.serialization.string(),
    timestamp: core.serialization.date(),
    status: core.serialization.string(),
    details: core.serialization.string().optional(),
});

export declare namespace NotionSyncHistoryItem {
    export interface Raw {
        id: string;
        timestamp: string;
        status: string;
        details?: string | null;
    }
}
