/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const NotionGenericSuccessResponse: core.serialization.ObjectSchema<
    serializers.NotionGenericSuccessResponse.Raw,
    DomeApi.NotionGenericSuccessResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string().optional(),
});

export declare namespace NotionGenericSuccessResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
    }
}
