/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const Pagination: core.serialization.ObjectSchema<serializers.Pagination.Raw, DomeApi.Pagination>;
export declare namespace Pagination {
    interface Raw {
        total: number;
        limit: number;
        offset: number;
        hasMore: boolean;
    }
}
