/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const Pagination: core.serialization.ObjectSchema<serializers.Pagination.Raw, DomeApi.Pagination> =
    core.serialization.object({
        total: core.serialization.number(),
        limit: core.serialization.number(),
        offset: core.serialization.number(),
        hasMore: core.serialization.boolean(),
    });

export declare namespace Pagination {
    export interface Raw {
        total: number;
        limit: number;
        offset: number;
        hasMore: boolean;
    }
}
