/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const ReprocessResponse: core.serialization.ObjectSchema<serializers.ReprocessResponse.Raw, DomeApi.ReprocessResponse>;
export declare namespace ReprocessResponse {
    interface Raw {
        success: boolean;
        message: string;
        reprocessedCount?: number | null;
    }
}
