/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const RootResponseService: core.serialization.ObjectSchema<
    serializers.RootResponseService.Raw,
    DomeApi.RootResponseService
> = core.serialization.object({
    name: core.serialization.string(),
    version: core.serialization.string(),
    environment: core.serialization.string(),
});

export declare namespace RootResponseService {
    export interface Raw {
        name: string;
        version: string;
        environment: string;
    }
}
