/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const RootResponseService: core.serialization.ObjectSchema<serializers.RootResponseService.Raw, DomeApi.RootResponseService>;
export declare namespace RootResponseService {
    interface Raw {
        name: string;
        version: string;
        environment: string;
    }
}
