/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { SearchErrorResponseError } from "./SearchErrorResponseError";

export const SearchErrorResponse: core.serialization.ObjectSchema<
    serializers.SearchErrorResponse.Raw,
    DomeApi.SearchErrorResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    error: SearchErrorResponseError,
});

export declare namespace SearchErrorResponse {
    export interface Raw {
        success: boolean;
        error: SearchErrorResponseError.Raw;
    }
}
