/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const SearchErrorResponseError: core.serialization.ObjectSchema<serializers.SearchErrorResponseError.Raw, DomeApi.SearchErrorResponseError>;
export declare namespace SearchErrorResponseError {
    interface Raw {
        code: string;
        message: string;
        details?: unknown | null;
    }
}
