/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { SearchResultItem } from "./SearchResultItem";
import { Pagination } from "./Pagination";

export const SearchResponse: core.serialization.ObjectSchema<serializers.SearchResponse.Raw, DomeApi.SearchResponse> =
    core.serialization.object({
        success: core.serialization.boolean(),
        results: core.serialization.list(SearchResultItem),
        pagination: Pagination,
        query: core.serialization.string(),
        message: core.serialization.string().optional(),
    });

export declare namespace SearchResponse {
    export interface Raw {
        success: boolean;
        results: SearchResultItem.Raw[];
        pagination: Pagination.Raw;
        query: string;
        message?: string | null;
    }
}
