/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const SearchErrorResponseError: core.serialization.ObjectSchema<
    serializers.SearchErrorResponseError.Raw,
    DomeApi.SearchErrorResponseError
> = core.serialization.object({
    code: core.serialization.string(),
    message: core.serialization.string(),
    details: core.serialization.unknown().optional(),
});

export declare namespace SearchErrorResponseError {
    export interface Raw {
        code: string;
        message: string;
        details?: unknown | null;
    }
}
