/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const SearchResultItem: core.serialization.ObjectSchema<serializers.SearchResultItem.Raw, DomeApi.SearchResultItem>;
export declare namespace SearchResultItem {
    interface Raw {
        id: string;
        title: string;
        summary: string;
        body?: string | null;
        category: string;
        mimeType: string;
        createdAt: number;
        updatedAt?: number | null;
        score: number;
    }
}
