/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { StreamingErrorDataError } from "./StreamingErrorDataError";
export declare const StreamingErrorData: core.serialization.ObjectSchema<serializers.StreamingErrorData.Raw, DomeApi.StreamingErrorData>;
export declare namespace StreamingErrorData {
    interface Raw {
        error: StreamingErrorDataError.Raw;
    }
}
