/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const StreamingErrorDataError: core.serialization.ObjectSchema<serializers.StreamingErrorDataError.Raw, DomeApi.StreamingErrorDataError>;
export declare namespace StreamingErrorDataError {
    interface Raw {
        code: string;
        message: string;
    }
}
