/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const SyncHistoryItem: core.serialization.ObjectSchema<serializers.SyncHistoryItem.Raw, DomeApi.SyncHistoryItem>;
export declare namespace SyncHistoryItem {
    interface Raw {
        id: string;
        timestamp: string;
        status: string;
        eventCount?: number | null;
        summary?: string | null;
    }
}
