/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { UnauthorizedErrorBodyError } from "./UnauthorizedErrorBodyError";
export declare const UnauthorizedErrorBody: core.serialization.ObjectSchema<serializers.UnauthorizedErrorBody.Raw, DomeApi.UnauthorizedErrorBody>;
export declare namespace UnauthorizedErrorBody {
    interface Raw {
        success?: boolean | null;
        error?: UnauthorizedErrorBodyError.Raw | null;
    }
}
