/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
export declare const UserProfile: core.serialization.ObjectSchema<serializers.UserProfile.Raw, DomeApi.UserProfile>;
export declare namespace UserProfile {
    interface Raw {
        id: string;
        email: string;
        name: string;
        role: string;
    }
}
