/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const UserProfile: core.serialization.ObjectSchema<serializers.UserProfile.Raw, DomeApi.UserProfile> =
    core.serialization.object({
        id: core.serialization.string(),
        email: core.serialization.string(),
        name: core.serialization.string(),
        role: core.serialization.string(),
    });

export declare namespace UserProfile {
    export interface Raw {
        id: string;
        email: string;
        name: string;
        role: string;
    }
}
