/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetNotesRequestCategory: core.serialization.Schema<serializers.GetNotesRequestCategory.Raw, DomeApi.GetNotesRequestCategory>;
export declare namespace GetNotesRequestCategory {
    type Raw = "note" | "code" | "document" | "article" | "other";
}
