/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type PostChatRequestMessagesItemRole = "user" | "assistant" | "system";
export declare const PostChatRequestMessagesItemRole: {
    readonly User: "user";
    readonly Assistant: "assistant";
    readonly System: "system";
};
