/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const ConfigureNotionOAuthBody: core.serialization.Schema<serializers.ConfigureNotionOAuthBody.Raw, DomeApi.ConfigureNotionOAuthBody>;
export declare namespace ConfigureNotionOAuthBody {
    interface Raw {
        clientId?: string | null;
        clientSecret?: string | null;
        redirectUri?: string | null;
    }
}
