/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { BadRequestErrorBodyError } from "./BadRequestErrorBodyError";

export const BadRequestErrorBody: core.serialization.ObjectSchema<
    serializers.BadRequestErrorBody.Raw,
    DomeApi.BadRequestErrorBody
> = core.serialization.object({
    success: core.serialization.boolean().optional(),
    error: BadRequestErrorBodyError.optional(),
});

export declare namespace BadRequestErrorBody {
    export interface Raw {
        success?: boolean | null;
        error?: BadRequestErrorBodyError.Raw | null;
    }
}
