/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { ChatErrorResponseError } from "./ChatErrorResponseError";

export const ChatErrorResponse: core.serialization.ObjectSchema<
    serializers.ChatErrorResponse.Raw,
    DomeApi.ChatErrorResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    error: ChatErrorResponseError,
});

export declare namespace ChatErrorResponse {
    export interface Raw {
        success: boolean;
        error: ChatErrorResponseError.Raw;
    }
}
