/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const ChatSource: core.serialization.ObjectSchema<serializers.ChatSource.Raw, DomeApi.ChatSource> =
    core.serialization.object({
        id: core.serialization.string(),
        type: core.serialization.string(),
        title: core.serialization.string().optional(),
        url: core.serialization.string().optional(),
    });

export declare namespace ChatSource {
    export interface Raw {
        id: string;
        type: string;
        title?: string | null;
        url?: string | null;
    }
}
