/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { ChatSuccessData } from "./ChatSuccessData";

export const ChatSuccessResponse: core.serialization.ObjectSchema<
    serializers.ChatSuccessResponse.Raw,
    DomeApi.ChatSuccessResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: ChatSuccessData,
});

export declare namespace ChatSuccessResponse {
    export interface Raw {
        success: boolean;
        data: ChatSuccessData.Raw;
    }
}
