/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const DeleteSuccessResponse: core.serialization.ObjectSchema<
    serializers.DeleteSuccessResponse.Raw,
    DomeApi.DeleteSuccessResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string(),
});

export declare namespace DeleteSuccessResponse {
    export interface Raw {
        success: boolean;
        message: string;
    }
}
