/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { DomeApiValidateTokenResponseUserProvider } from "./DomeApiValidateTokenResponseUserProvider";
import { UserProfile } from "./UserProfile";

export const DomeApiValidateTokenResponseUser: core.serialization.ObjectSchema<
    serializers.DomeApiValidateTokenResponseUser.Raw,
    DomeApi.DomeApiValidateTokenResponseUser
> = core.serialization
    .object({
        provider: DomeApiValidateTokenResponseUserProvider,
    })
    .extend(UserProfile);

export declare namespace DomeApiValidateTokenResponseUser {
    export interface Raw extends UserProfile.Raw {
        provider: DomeApiValidateTokenResponseUserProvider.Raw;
    }
}
