/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { DomeApiValidateTokenResponseUser } from "./DomeApiValidateTokenResponseUser";

export const DomeApiValidateTokenResponse: core.serialization.ObjectSchema<
    serializers.DomeApiValidateTokenResponse.Raw,
    DomeApi.DomeApiValidateTokenResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    user: DomeApiValidateTokenResponseUser,
});

export declare namespace DomeApiValidateTokenResponse {
    export interface Raw {
        success: boolean;
        user: DomeApiValidateTokenResponseUser.Raw;
    }
}
