/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { ErrorResponseError } from "./ErrorResponseError";

export const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, DomeApi.ErrorResponse> =
    core.serialization.object({
        success: core.serialization.boolean(),
        error: ErrorResponseError,
    });

export declare namespace ErrorResponse {
    export interface Raw {
        success: boolean;
        error: ErrorResponseError.Raw;
    }
}
