/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const GithubRepoResponse: core.serialization.ObjectSchema<
    serializers.GithubRepoResponse.Raw,
    DomeApi.GithubRepoResponse
> = core.serialization.object({
    id: core.serialization.string(),
    owner: core.serialization.string(),
    name: core.serialization.string(),
});

export declare namespace GithubRepoResponse {
    export interface Raw {
        id: string;
        owner: string;
        name: string;
    }
}
