/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { HealthResponseMetricsCounters } from "./HealthResponseMetricsCounters";

export const HealthResponseMetrics: core.serialization.ObjectSchema<
    serializers.HealthResponseMetrics.Raw,
    DomeApi.HealthResponseMetrics
> = core.serialization.object({
    counters: HealthResponseMetricsCounters,
});

export declare namespace HealthResponseMetrics {
    export interface Raw {
        counters: HealthResponseMetricsCounters.Raw;
    }
}
