/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { InternalServerErrorBodyError } from "./InternalServerErrorBodyError";

export const InternalServerErrorBody: core.serialization.ObjectSchema<
    serializers.InternalServerErrorBody.Raw,
    DomeApi.InternalServerErrorBody
> = core.serialization.object({
    success: core.serialization.boolean().optional(),
    error: InternalServerErrorBodyError.optional(),
});

export declare namespace InternalServerErrorBody {
    export interface Raw {
        success?: boolean | null;
        error?: InternalServerErrorBodyError.Raw | null;
    }
}
