/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { NoteCategory } from "./NoteCategory";
import { NoteMimeType } from "./NoteMimeType";

export const Note: core.serialization.ObjectSchema<serializers.Note.Raw, DomeApi.Note> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.string().optional(),
    category: NoteCategory,
    title: core.serialization.string().optional(),
    content: core.serialization.string().optional(),
    mimeType: NoteMimeType,
    size: core.serialization.number(),
    createdAt: core.serialization.date(),
    url: core.serialization.string().optional(),
    customMetadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace Note {
    export interface Raw {
        id: string;
        userId?: string | null;
        category: NoteCategory.Raw;
        title?: string | null;
        content?: string | null;
        mimeType: NoteMimeType.Raw;
        size: number;
        createdAt: string;
        url?: string | null;
        customMetadata?: Record<string, unknown> | null;
    }
}
