/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const NotionOAuthUrlResponse: core.serialization.ObjectSchema<
    serializers.NotionOAuthUrlResponse.Raw,
    DomeApi.NotionOAuthUrlResponse
> = core.serialization.object({
    url: core.serialization.string(),
});

export declare namespace NotionOAuthUrlResponse {
    export interface Raw {
        url: string;
    }
}
