/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const NotionWorkspaceResponse: core.serialization.ObjectSchema<
    serializers.NotionWorkspaceResponse.Raw,
    DomeApi.NotionWorkspaceResponse
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
});

export declare namespace NotionWorkspaceResponse {
    export interface Raw {
        id: string;
        name: string;
    }
}
