/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const RegisterResponse: core.serialization.ObjectSchema<
    serializers.RegisterResponse.Raw,
    DomeApi.RegisterResponse
> = core.serialization.object({
    token: core.serialization.string(),
});

export declare namespace RegisterResponse {
    export interface Raw {
        token: string;
    }
}
