/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { RootResponseService } from "./RootResponseService";

export const RootResponse: core.serialization.ObjectSchema<serializers.RootResponse.Raw, DomeApi.RootResponse> =
    core.serialization.object({
        message: core.serialization.string(),
        service: RootResponseService,
        description: core.serialization.string(),
    });

export declare namespace RootResponse {
    export interface Raw {
        message: string;
        service: RootResponseService.Raw;
        description: string;
    }
}
