/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const SearchResultItem: core.serialization.ObjectSchema<
    serializers.SearchResultItem.Raw,
    DomeApi.SearchResultItem
> = core.serialization.object({
    id: core.serialization.string(),
    title: core.serialization.string(),
    summary: core.serialization.string(),
    body: core.serialization.string().optional(),
    category: core.serialization.string(),
    mimeType: core.serialization.string(),
    createdAt: core.serialization.number(),
    updatedAt: core.serialization.number().optional(),
    score: core.serialization.number(),
});

export declare namespace SearchResultItem {
    export interface Raw {
        id: string;
        title: string;
        summary: string;
        body?: string | null;
        category: string;
        mimeType: string;
        createdAt: number;
        updatedAt?: number | null;
        score: number;
    }
}
