/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { StreamingErrorDataError } from "./StreamingErrorDataError";

export const StreamingErrorData: core.serialization.ObjectSchema<
    serializers.StreamingErrorData.Raw,
    DomeApi.StreamingErrorData
> = core.serialization.object({
    error: StreamingErrorDataError,
});

export declare namespace StreamingErrorData {
    export interface Raw {
        error: StreamingErrorDataError.Raw;
    }
}
