/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { Pagination } from "./Pagination";

export const StreamingMetadata: core.serialization.ObjectSchema<
    serializers.StreamingMetadata.Raw,
    DomeApi.StreamingMetadata
> = core.serialization.object({
    pagination: Pagination,
    query: core.serialization.string(),
});

export declare namespace StreamingMetadata {
    export interface Raw {
        pagination: Pagination.Raw;
        query: string;
    }
}
