/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const StreamingErrorDataError: core.serialization.ObjectSchema<
    serializers.StreamingErrorDataError.Raw,
    DomeApi.StreamingErrorDataError
> = core.serialization.object({
    code: core.serialization.string(),
    message: core.serialization.string(),
});

export declare namespace StreamingErrorDataError {
    export interface Raw {
        code: string;
        message: string;
    }
}
