/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { SearchResultItem } from "./SearchResultItem";

export const StreamingResultData: core.serialization.ObjectSchema<
    serializers.StreamingResultData.Raw,
    DomeApi.StreamingResultData
> = core.serialization.object({
    data: SearchResultItem,
});

export declare namespace StreamingResultData {
    export interface Raw {
        data: SearchResultItem.Raw;
    }
}
