/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { SyncHistoryItem } from "./SyncHistoryItem";

export const SyncHistoryResponse: core.serialization.Schema<
    serializers.SyncHistoryResponse.Raw,
    DomeApi.SyncHistoryResponse
> = core.serialization.list(SyncHistoryItem);

export declare namespace SyncHistoryResponse {
    export type Raw = SyncHistoryItem.Raw[];
}
