/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const SyncHistoryItem: core.serialization.ObjectSchema<
    serializers.SyncHistoryItem.Raw,
    DomeApi.SyncHistoryItem
> = core.serialization.object({
    id: core.serialization.string(),
    timestamp: core.serialization.date(),
    status: core.serialization.string(),
    eventCount: core.serialization.number().optional(),
    summary: core.serialization.string().optional(),
});

export declare namespace SyncHistoryItem {
    export interface Raw {
        id: string;
        timestamp: string;
        status: string;
        eventCount?: number | null;
        summary?: string | null;
    }
}
