/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";

export const UserProfileAuthProvider: core.serialization.Schema<
    serializers.UserProfileAuthProvider.Raw,
    DomeApi.UserProfileAuthProvider
> = core.serialization.enum_(["local", "privy", "google", "github"]);

export declare namespace UserProfileAuthProvider {
    export type Raw = "local" | "privy" | "google" | "github";
}
