/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DomeApi from "../../api/index";
import * as core from "../../core";
import { UserProfile } from "./UserProfile";

export const ValidateTokenResponse: core.serialization.ObjectSchema<
    serializers.ValidateTokenResponse.Raw,
    DomeApi.ValidateTokenResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    user: UserProfile,
});

export declare namespace ValidateTokenResponse {
    export interface Raw {
        success: boolean;
        user: UserProfile.Raw;
    }
}
