/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as DomeApi from "../../../index";
export declare namespace ContentSync {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class ContentSync {
    protected readonly _options: ContentSync.Options;
    constructor(_options: ContentSync.Options);
    /**
     * @param {string} userId
     * @param {ContentSync.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link DomeApi.UnauthorizedError}
     * @throws {@link DomeApi.ForbiddenError}
     * @throws {@link DomeApi.NotFoundError}
     * @throws {@link DomeApi.InternalServerError}
     *
     * @example
     *     await client.contentSync.getUserSyncHistory("user_123")
     */
    getUserSyncHistory(userId: string, requestOptions?: ContentSync.RequestOptions): Promise<DomeApi.SyncHistoryResponse>;
    /**
     * @param {string} syncPlanId
     * @param {ContentSync.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link DomeApi.UnauthorizedError}
     * @throws {@link DomeApi.NotFoundError}
     * @throws {@link DomeApi.InternalServerError}
     *
     * @example
     *     await client.contentSync.getSyncPlanHistory("plan_abc")
     */
    getSyncPlanHistory(syncPlanId: string, requestOptions?: ContentSync.RequestOptions): Promise<DomeApi.SyncHistoryResponse>;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
