name = "constellation"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "dome-meta"
database_id = "ac198406-1036-495e-b0f1-b61f7c9ecbdf"
preview_database_id = "672837d0-28fc-4ac8-9144-86653a2d0965"
migrations_dir = "services/dome-api/migrations"   # mono-repo friendly

[[vectorize]]
binding = "VECTORIZE"
index_name = "dome-notes"

[[queues.consumers]]
queue = "new-data"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3

# Workers AI binding
[ai]
binding = "AI"
