name = "constellation"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

# Queue consumer configuration
[[queues.consumers]]
queue = "EMBED_QUEUE"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3

# Optional dead letter queue
[[queues.producers]]
binding = "EMBED_DEAD"
queue = "embed-dead-letter"

# Vectorize binding
[[vectorize]]
binding = "VECTORIZE"
index_name = "dome-notes"

# Workers AI binding
[ai]
binding = "AI"

# For local development
[dev]
port = 8788

[vars]
VERSION = "0.1.0"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }