name = "constellation"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

# Queue consumer configuration
[[queues.consumers]]
queue = "new-content-constellation"
max_batch_size = 5  # Reduced from 10 to prevent memory issues
max_batch_timeout = 5
max_retries = 3
max_concurrency = 3  # Reduced to lower concurrent processing
dead_letter_queue = "embed-dead-letter"

# Dead letter queue producer
[[queues.producers]]
binding = "EMBED_DEAD"
queue = "embed-dead-letter"

# Vectorize binding
[[vectorize]]
binding = "VECTORIZE"
index_name = "dome-notes"

# Workers AI binding
[ai]
binding = "AI"

# Service binding for Silo
[[services]]
binding = "SILO"
service = "silo"

# For local development
[dev]
port = 8788
local_protocol = "https"

[vars]
VERSION = "1.0.0"
LOG_LEVEL = "debug"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
