/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../index";

export interface DomeApiValidateTokenResponse {
    success: boolean;
    user: DomeApi.DomeApiValidateTokenResponseUser;
}
