/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../index";

export interface DomeApiValidateTokenResponseUser extends DomeApi.UserProfile {
    /** The authentication provider used. */
    provider: DomeApi.DomeApiValidateTokenResponseUserProvider;
}
