/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The authentication provider used.
 */
export type DomeApiValidateTokenResponseUserProvider = "local" | "privy" | "google" | "github";
export const DomeApiValidateTokenResponseUserProvider = {
    Local: "local",
    Privy: "privy",
    Google: "google",
    Github: "github",
} as const;
