/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../index";

export interface ForbiddenErrorBody {
    success?: boolean;
    error?: DomeApi.ForbiddenErrorBodyError;
}
