/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../index";

export interface HealthResponse {
    status: "ok";
    timestamp: Date;
    service: string;
    version: string;
    metrics?: DomeApi.HealthResponseMetrics;
}
