/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../index";

export interface UserProfile {
    id: string;
    email: string;
    name?: string;
    role: string;
    emailVerified?: boolean;
    isActive?: boolean;
    createdAt: Date;
    updatedAt: Date;
    lastLoginAt?: Date;
    authProvider?: DomeApi.UserProfileAuthProvider;
    providerAccountId?: string;
}
