/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UserProfileAuthProvider = "local" | "privy" | "google" | "github";
export const UserProfileAuthProvider = {
    Local: "local",
    Privy: "privy",
    Google: "google",
    Github: "github",
} as const;
