/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as DomeApi from "../../../index";
export declare namespace Ai {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Ai {
    protected readonly _options: Ai.Options;
    constructor(_options: Ai.Options);
    /**
     * @param {DomeApi.ReprocessBody} request
     * @param {Ai.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link DomeApi.BadRequestError}
     * @throws {@link DomeApi.UnauthorizedError}
     * @throws {@link DomeApi.NotFoundError}
     * @throws {@link DomeApi.InternalServerError}
     *
     * @example
     *     await client.ai.reprocessAiMetadata({
     *         contentId: "content_abc123"
     *     })
     */
    reprocessAiMetadata(request: DomeApi.ReprocessBody, requestOptions?: Ai.RequestOptions): Promise<DomeApi.ReprocessResponse>;
    /**
     * @param {DomeApi.BulkReprocessBody} request
     * @param {Ai.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link DomeApi.BadRequestError}
     * @throws {@link DomeApi.UnauthorizedError}
     * @throws {@link DomeApi.InternalServerError}
     *
     * @example
     *     await client.ai.bulkReprocessAiMetadata({
     *         contentIds: ["contentIds"]
     *     })
     */
    bulkReprocessAiMetadata(request: DomeApi.BulkReprocessBody, requestOptions?: Ai.RequestOptions): Promise<DomeApi.BulkReprocessResponse>;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
