name = "dome-cron"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

[[queues.producers]]
binding = "EVENTS"
queue = "dome-events"

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "dome-meta"
database_id = "ac198406-1036-495e-b0f1-b61f7c9ecbdf"
preview_database_id = "672837d0-28fc-4ac8-9144-86653a2d0965"
migrations_dir = "services/dome-api/migrations"   # mono-repo friendly

# Scheduled cron triggers
[triggers]
crons = [
  "*/5 * * * *",  # Every 5 minutes for reminder processing
  "*/15 * * * *"  # Every 15 minutes for DLQ monitoring
]

# For local development
[dev]
port = 8788

[vars]
VERSION = "0.1.0"
ENVIRONMENT = "development"

# DLQ monitoring configuration
SILO_API_URL = "http://localhost:8787"
INTERNAL_API_KEY = "dev-internal-api-key"
DLQ_ALERT_THRESHOLD = "100"
DLQ_ERROR_TYPE_THRESHOLD = "50"
DLQ_AUTO_REPROCESS = "true"

# Environment-specific configurations
[env.production]
vars = {
  ENVIRONMENT = "production",
  SILO_API_URL = "https://silo.dome.production.workers.dev",
  DLQ_ALERT_THRESHOLD = "50",
  DLQ_ERROR_TYPE_THRESHOLD = "25",
  DLQ_AUTO_REPROCESS = "true"
}

[env.staging]
vars = {
  ENVIRONMENT = "staging",
  SILO_API_URL = "https://silo.dome.staging.workers.dev",
  DLQ_ALERT_THRESHOLD = "100",
  DLQ_ERROR_TYPE_THRESHOLD = "50",
  DLQ_AUTO_REPROCESS = "true"
}
command = "pnpm build"
