name = "dome-cron"
main = "src/index.ts"
compatibility_date = "2023-05-18"
inject = "../../wrangler.shared.toml"

# Build configuration
[build]
command = "pnpm build"

# Scheduled cron trigger (every 5 minutes)
[triggers]
crons = ["*/5 * * * *"]

[vars]
ENVIRONMENT = "development"
VERSION = "0.1.0"

# Environment-specific configurations
[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }