name = "dome-cron"
main = "src/index.ts"
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_als"]

[[queues.producers]]
binding = "EVENTS"
queue = "dome-events"

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "dome-meta"
database_id = "ac198406-1036-495e-b0f1-b61f7c9ecbdf"
preview_database_id = "672837d0-28fc-4ac8-9144-86653a2d0965"
migrations_dir = "services/dome-api/migrations"   # mono-repo friendly

# Scheduled cron trigger (every 5 minutes)
[triggers]
crons = ["*/5 * * * *"]

# For local development
[dev]
port = 8788

[vars]
VERSION = "0.1.0"
ENVIRONMENT = "development"

# Environment-specific configurations
[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
command = "pnpm build"
