// ledger-runs: the per-run lifecycle accessors for the `runs` table.
// Owns the run id generator, the run-status state transitions, the read
// surface (`queryRuns`, `getRun`), and the
// orphan-detection helpers used by `dome inspect orphan-runs` /
// `--orphan-runs --fail`.
//
// Normative references:
//   - docs/wiki/specs/run-ledger.md §"Tables — runs" (column shape +
//     status enum + run id format).
//   - docs/wiki/specs/run-ledger.md §"Run lifecycle" (the run states +
//     the engine-side write points: queued at enqueue, running at start
//     of Processor.run(), terminal at end; failed-run try/catch + orphan
//     detection on crash between running and terminal).
//   - docs/wiki/specs/run-ledger.md §"Query surface (CLI)" — the shape
//     of `dome inspect runs ...` queries.
//
// Structural fences this file upholds:
//   - docs/wiki/invariants/EVERY_PROCESSOR_RUN_IS_LEDGERED.md §"Structural
//     enforcement" — the engine writes `insertQueued` synchronously before
//     calling `processor.run()`, `markRunning` at the start of `run()`,
//     one terminal mark at the end. Crashes between
//     `markRunning` and the terminal mark leave rows visible to
//     `orphanRuns(...)`.
//
// Lifecycle invariants (the state machine this file encodes):
//
//   insertQueued        → row created, status="queued".
//
//   markRunning         → "queued" → "running". UPDATE filters by
//                         status="queued" so a double-mark is a no-op
//                         (concurrent dispatcher race protection).
//
//   markSucceeded       → "running" → "succeeded". Terminal. Captures
//                         effect_hashes_json, cost_usd, duration_ms,
//                         output_commit, finished_at. UPDATE filters
//                         by status="running".
//
//   markFailed          → "running" → "failed". Terminal. Captures
//                         error, duration_ms, finished_at. UPDATE filters
//                         by status="running".
//
//   markTimedOut        → "running" → "timed_out". Terminal. Captures
//                         structured error JSON, duration_ms, finished_at.
//                         UPDATE filters by status="running".
//
//   markCancelled       → "running" → "cancelled". Terminal. Captures
//                         structured error JSON, duration_ms, finished_at.
//                         UPDATE filters by status="running".
//
//   markSkipped         → "queued" → "skipped". Terminal. Captures
//                         finished_at and optionally error/reason JSON.
//                         UPDATE filters by status="queued". Used for
//                         any not-invoked run, including idempotency
//                         dedup and pre-run policy denial.
//
// `failOrphanedRuns` / `failRunIfCurrent` are the recovery paths for engine crashes between
// `markRunning` and a terminal mark — it transitions stuck-running rows
// to `failed` so the audit history reaches a terminal state. v1.0
// surfaces orphans via `dome check` and advanced `dome inspect runs`; recovery
// follows the engine-asks model: `dome.health.orphan-run-recovery-questions`
// emits a QuestionEffect per orphan row, and the user resolves `fail` /
// `ignore` via `dome resolve` (the answer-handler invokes
// `failRunIfCurrent`).
//
// Imports (tight by design — the ledger is the SQLite boundary):
//   - `node:crypto` for the random suffix in `newRunId`.
//   - `./db` for the `LedgerDb` handle.
//   - `../core/processor` for the `ProcessorPhase` type.
//   - `../core/source-ref` for the `CommitOid` brand + `commitOid` helper.
//   - `../engine/core/runner-contract` for the shared RunId and structured
//     execution-error type contracts.
//
// House-style notes (mirrors src/outbox/dispatch.ts, src/projections/jobs.ts):
//   - `type X = { ... }` aliases (not `interface`), every field `readonly`.
//   - JSON columns (`effect_hashes_json`, `trigger_payload_json`) serialized
//     via `JSON.stringify` on write, parsed on read.
//   - INSERT uses simple `INSERT` (no `OR IGNORE`): the `id` is a
//     UUID-like generated by `newRunId`, so collisions are practically
//     impossible. A duplicate-id INSERT will throw — that's a programmer
//     error worth surfacing, not a silent dedup.
//   - Returned arrays are `Object.freeze`'d.
//   - `noUncheckedIndexedAccess` discipline: row arrays are mapped
//     functionally; index access into `.all()` results checks `=== undefined`.

import { randomBytes } from "node:crypto";
import { z } from "zod";

import { JsonValueSchema } from "../core/effect";
import type { ProcessorPhase } from "../core/processor";
import { commitOid, type CommitOid } from "../core/source-ref";
import {
  type ProcessorCancelledExecutionError,
  type ProcessorFailedExecutionError,
  type ProcessorTimeoutExecutionError,
  type RunId,
} from "../engine/core/runner-contract";
import { parseJsonColumn } from "../sqlite/row-json";
import { rowCodec } from "../sqlite/row-codec";
import { mapRows } from "../sqlite/rows";
import type { LedgerDb } from "./db";
import { limitClause } from "./limits";

// ----- Branded RunId --------------------------------------------------------
//
// The `RunId` brand is owned by `../engine/core/runner-contract` (the engine ↔
// runtime contract that the ledger consumes). Re-exported here so existing
// callers — `src/processors/runtime.ts`, the ledger accessors below — can
// keep importing it from the ledger surface unchanged.

export type { RunId };

// ----- Run lifecycle status -------------------------------------------------

/**
 * The closed set of lifecycle states per spec §"Run lifecycle".
 *
 * - `queued`    — engine enqueued the invocation; processor.run() not yet started.
 * - `running`   — processor.run() is executing.
 * - `succeeded` — processor.run() returned without throwing.
 * - `failed`    — processor.run() threw, or returned an invalid Effect, or
 *                 the orphan-recovery path transitioned a stuck-running row.
 * - `skipped`   — the run was not invoked (idempotency dedup, policy denial, etc.).
 * - `timed_out` — processor execution exceeded its configured deadline.
 * - `cancelled` — processor execution was cancelled by shutdown/re-drive.
 */
export type RunStatus =
  | "queued"
  | "running"
  | "succeeded"
  | "failed"
  | "skipped"
  | "timed_out"
  | "cancelled";

// ----- Trigger kind --------------------------------------------------------

/**
 * The trigger kinds per spec §"Tables — runs" `trigger_kind` column.
 * Mirrors the `kind` discriminator of `Trigger` in `src/core/processor.ts`;
 * stored as a plain string in SQLite (the full Trigger payload is captured
 * separately via `trigger_payload_json`).
 */
export type TriggerKind =
  | "signal"
  | "path"
  | "schedule"
  | "answer"
  | "command"
  | "job";

// ----- newRunId -------------------------------------------------------------

/**
 * Length of the random suffix in a RunId. Per spec: `<6-char-rand>`.
 * Six hex chars = 24 bits of entropy = ~16M values; within a single
 * millisecond bucket the collision probability is negligible.
 */
const RUN_ID_RAND_LEN = 6;

/**
 * Generate a fresh RunId in the canonical `run_<unix-ms>_<6-char-rand>`
 * format. The default `random` source uses `node:crypto.randomBytes` for
 * cryptographic-quality entropy; tests can pass a deterministic stub.
 *
 * The `random` parameter returns the raw 6-char-suffix string directly
 * (not bytes) — this keeps the test stub trivial (`() => "abcdef"`).
 */
export function newRunId(now: Date, random?: () => string): RunId {
  const rand = random === undefined ? defaultRandomSuffix() : random();
  return `run_${now.getTime()}_${rand}` as RunId;
}

function defaultRandomSuffix(): string {
  // 3 bytes = 6 hex chars; matches RUN_ID_RAND_LEN.
  return randomBytes(RUN_ID_RAND_LEN / 2).toString("hex");
}

// ----- Public types ---------------------------------------------------------

export type InsertQueuedOpts = {
  readonly id: RunId;
  readonly proposalId: string | null;
  readonly processorId: string;
  readonly processorVersion: string;
  readonly phase: ProcessorPhase;
  readonly inputCommit: CommitOid;
  readonly triggerKind: TriggerKind;
  /** JSON-serializable payload captured for audit (the input that fired the trigger). */
  readonly triggerPayload: unknown;
  readonly startedAt: Date;
};

export type MarkSucceededOpts = {
  readonly id: RunId;
  /** sha256s of each emitted effect; empty array is valid (no effects emitted). */
  readonly effectHashes: ReadonlyArray<string>;
  readonly costUsd: number | null;
  readonly durationMs: number;
  readonly outputCommit: CommitOid | null;
  readonly finishedAt: Date;
};

export type MarkFailedOpts = {
  readonly id: RunId;
  readonly error: string | ProcessorFailedExecutionError;
  readonly costUsd?: number | null;
  readonly durationMs: number;
  readonly finishedAt: Date;
};

export type MarkTimedOutOpts = {
  readonly id: RunId;
  readonly error: ProcessorTimeoutExecutionError;
  readonly costUsd?: number | null;
  readonly durationMs: number;
  readonly finishedAt: Date;
};

export type MarkCancelledOpts = {
  readonly id: RunId;
  readonly error: ProcessorCancelledExecutionError;
  readonly costUsd?: number | null;
  readonly durationMs: number;
  readonly finishedAt: Date;
};

export type MarkSkippedOpts = {
  readonly id: RunId;
  readonly finishedAt: Date;
  /**
   * Optional not-invoked reason. Idempotency skips usually leave this null;
   * policy denials and quarantine skips should write structured JSON.
   */
  readonly error?: string;
};

export type FailRunIfCurrentOpts = {
  readonly id: string;
  readonly startedAt: string;
  readonly processorId: string;
  readonly processorVersion: string;
  readonly phase: "adoption" | "garden" | "view";
  readonly error: string;
  readonly finishedAt: Date;
};

/**
 * Bulk-update `output_commit` for the named successful runs. Called by the
 * engine's adoption loop (`src/engine/core/adopt.ts`) once `makeClosureCommit`
 * returns a non-null OID — `markSucceeded` writes NULL into the column at
 * processor-run-terminal time (because the closure commit doesn't exist
 * yet), and this accessor lands the OID after the fact.
 *
 * The two-write pattern is intentional, NOT a layering bug — see
 * docs/wiki/gotchas/run-succeeded-before-closure.md. The run lifecycle is
 * bounded by `processor.run()`, not by the engine's adoption cycle; a run
 * whose effects were all rejected by the broker contributed nothing to the
 * closure commit and must still reach `succeeded`.
 */
export type UpdateOutputCommitOpts = {
  readonly runIds: ReadonlyArray<RunId>;
  readonly outputCommit: CommitOid;
};

/**
 * Row shape returned by `queryRuns` / `getRun` / `orphanRuns`. JSON columns
 * are deserialized. Nullable columns are typed `T | null` (not `T | undefined`)
 * so SQL NULL maps cleanly under `exactOptionalPropertyTypes`.
 */
export type RunRow = {
  readonly id: RunId;
  readonly proposalId: string | null;
  readonly processorId: string;
  readonly processorVersion: string;
  readonly phase: ProcessorPhase;
  readonly inputCommit: CommitOid;
  readonly outputCommit: CommitOid | null;
  readonly status: RunStatus;
  readonly effectHashes: ReadonlyArray<string>;
  readonly costUsd: number | null;
  readonly durationMs: number | null;
  readonly error: string | null;
  readonly triggerKind: TriggerKind;
  readonly triggerPayload: unknown;
  readonly startedAt: string;
  readonly finishedAt: string | null;
};

export type RunSummaryRow = Pick<
  RunRow,
  | "id"
  | "processorId"
  | "processorVersion"
  | "phase"
  | "status"
  | "durationMs"
  | "error"
  | "triggerKind"
  | "startedAt"
  | "finishedAt"
>;

export type RunsQueryFilter = {
  readonly processorId?: string;
  readonly phase?: ProcessorPhase | ReadonlyArray<ProcessorPhase>;
  readonly status?: RunStatus;
  /** ISO-8601 lower bound on `started_at`. */
  readonly sinceIso?: string;
  readonly limit?: number;
};

export const ACTIVE_PROBLEM_RUN_STATUSES: ReadonlySet<RunStatus> = new Set([
  "failed",
  "timed_out",
  "cancelled",
]);

export type SumCostUsdByProcessorPrefixOpts = {
  readonly processorIdPrefix: string;
  readonly sinceIso: string;
};

/**
 * One row of the per-processor spend aggregation backing
 * `dome inspect cost` (docs/wiki/specs/run-ledger.md §"Query surface
 * (CLI)"). `runs` counts cost-bearing runs only — rows whose `cost_usd`
 * is NULL never billed a provider and are not spend evidence.
 */
export type ProcessorCostRow = {
  readonly processorId: string;
  readonly runs: number;
  readonly totalCostUsd: number;
  readonly todayCostUsd: number;
};

export type AggregateCostUsdByProcessorOpts = {
  /** ISO-8601 lower bound on `started_at` — the report window. */
  readonly sinceIso: string;
  /** ISO-8601 start-of-local-day — the "today" split inside the window. */
  readonly todayIso: string;
};

// ----- SQL ------------------------------------------------------------------

const INSERT_QUEUED_SQL = `
INSERT INTO runs (
  id, proposal_id, processor_id, processor_version, phase,
  input_commit, output_commit, status, effect_hashes_json,
  cost_usd, duration_ms, error, trigger_kind, trigger_payload_json,
  started_at, finished_at
) VALUES (?, ?, ?, ?, ?, ?, NULL, 'queued', '[]', NULL, NULL, NULL, ?, ?, ?, NULL)
`.trim();

const MARK_RUNNING_SQL = `
UPDATE runs
SET status = 'running'
WHERE id = ? AND status = 'queued'
`.trim();

const MARK_SUCCEEDED_SQL = `
UPDATE runs
SET status = 'succeeded',
    effect_hashes_json = ?,
    cost_usd = ?,
    duration_ms = ?,
    output_commit = ?,
    finished_at = ?
WHERE id = ? AND status = 'running'
`.trim();

const MARK_FAILED_SQL = `
UPDATE runs
SET status = 'failed',
    error = ?,
    cost_usd = ?,
    duration_ms = ?,
    finished_at = ?
WHERE id = ? AND status = 'running'
`.trim();

const MARK_TIMED_OUT_SQL = `
UPDATE runs
SET status = 'timed_out',
    error = ?,
    cost_usd = ?,
    duration_ms = ?,
    finished_at = ?
WHERE id = ? AND status = 'running'
`.trim();

const MARK_CANCELLED_SQL = `
UPDATE runs
SET status = 'cancelled',
    error = ?,
    cost_usd = ?,
    duration_ms = ?,
    finished_at = ?
WHERE id = ? AND status = 'running'
`.trim();

const MARK_SKIPPED_SQL = `
UPDATE runs
SET status = 'skipped',
    error = ?,
    finished_at = ?
WHERE id = ? AND status = 'queued'
`.trim();

// `updateOutputCommit` is parameterized per-call because the `IN (...)` set
// is variable-length; the SQL template is composed inline. Filters by
// `status = 'succeeded' AND output_commit IS NULL` so the OID lands at most
// once per run (defense against a re-driven adoption loop replaying the
// same runIds against a different closure commit).
const UPDATE_OUTPUT_COMMIT_SQL_PREFIX = `
UPDATE runs
SET output_commit = ?
WHERE status = 'succeeded' AND output_commit IS NULL AND id IN (
`.trim();

const SELECT_BASE_SQL = `
SELECT id, proposal_id, processor_id, processor_version, phase,
       input_commit, output_commit, status, effect_hashes_json,
       cost_usd, duration_ms, error, trigger_kind, trigger_payload_json,
       started_at, finished_at
FROM runs
`.trim();

const SELECT_SUMMARY_BASE_SQL = `
SELECT id, processor_id, processor_version, phase, status, duration_ms,
       error, trigger_kind, started_at, finished_at
FROM runs
`.trim();

const SELECT_BY_ID_SQL = `${SELECT_BASE_SQL} WHERE id = ?`;

const SUM_COST_USD_BY_PROCESSOR_PREFIX_SQL = `
SELECT COALESCE(SUM(cost_usd), 0) AS cost_usd
FROM runs
WHERE started_at >= ?
  AND cost_usd IS NOT NULL
  AND (processor_id = ? OR substr(processor_id, 1, ?) = ?)
`.trim();

// Sibling of SUM_COST_USD_BY_PROCESSOR_PREFIX_SQL: same `cost_usd IS NOT
// NULL` posture and `started_at >= ?` bound, grouped per processor for the
// `dome inspect cost` report. Placeholders bind in textual order: the
// today-split bound (SELECT clause) first, then the window bound (WHERE).
const AGGREGATE_COST_USD_BY_PROCESSOR_SQL = `
SELECT processor_id,
       COUNT(*) AS runs,
       COALESCE(SUM(cost_usd), 0) AS total_cost_usd,
       COALESCE(SUM(CASE WHEN started_at >= ? THEN cost_usd ELSE 0 END), 0) AS today_cost_usd
FROM runs
WHERE started_at >= ?
  AND cost_usd IS NOT NULL
GROUP BY processor_id
ORDER BY total_cost_usd DESC, processor_id ASC
`.trim();

const ORPHAN_RUNS_SQL = `
${SELECT_BASE_SQL}
WHERE status = 'running' AND started_at < ?
ORDER BY started_at
`.trim();

const LATEST_ACTIVE_PROBLEM_WHERE_SQL = `
WHERE status IN ('failed', 'timed_out', 'cancelled')
  AND NOT (
    status = 'failed'
    AND (
      error LIKE 'orphaned-run:%'
      OR error = 'dome.health: mark orphaned processor run failed'
    )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM runs AS newer
    WHERE newer.processor_id = runs.processor_id
      AND (
        newer.started_at > runs.started_at
        OR (newer.started_at = runs.started_at AND newer.id > runs.id)
      )
  )
`.trim();

const LATEST_ACTIVE_PROBLEM_RUNS_SQL = `
${SELECT_BASE_SQL}
${LATEST_ACTIVE_PROBLEM_WHERE_SQL}
ORDER BY started_at DESC, id DESC
`.trim();

const COUNT_LATEST_ACTIVE_PROBLEM_RUNS_SQL = `
SELECT COUNT(*) AS count
FROM runs
${LATEST_ACTIVE_PROBLEM_WHERE_SQL}
`.trim();

const FAIL_ORPHANS_SQL = `
UPDATE runs
SET status = 'failed',
    error = 'orphaned-run: engine crash detected; transitioned by failOrphanedRuns',
    finished_at = ?
WHERE status = 'running' AND started_at < ?
`.trim();

const FAIL_RUN_IF_CURRENT_SQL = `
UPDATE runs
SET status = 'failed',
    error = ?,
    duration_ms = ?,
    finished_at = ?
WHERE id = ? AND status = 'running' AND started_at = ?
  AND processor_id = ? AND processor_version = ? AND phase = ?
`.trim();

// ----- Raw row shape --------------------------------------------------------

type RunRawRow = {
  readonly id: string;
  readonly proposal_id: string | null;
  readonly processor_id: string;
  readonly processor_version: string;
  readonly phase: string;
  readonly input_commit: string;
  readonly output_commit: string | null;
  readonly status: string;
  readonly effect_hashes_json: string;
  readonly cost_usd: number | null;
  readonly duration_ms: number | null;
  readonly error: string | null;
  readonly trigger_kind: string;
  readonly trigger_payload_json: string;
  readonly started_at: string;
  readonly finished_at: string | null;
};

type RunSummaryRawRow = {
  readonly id: string;
  readonly processor_id: string;
  readonly processor_version: string;
  readonly phase: string;
  readonly status: string;
  readonly duration_ms: number | null;
  readonly error: string | null;
  readonly trigger_kind: string;
  readonly started_at: string;
  readonly finished_at: string | null;
};

type SumCostRawRow = {
  readonly cost_usd: number | null;
};

type ProcessorCostRawRow = {
  readonly processor_id: string;
  readonly runs: number;
  readonly total_cost_usd: number;
  readonly today_cost_usd: number;
};

type CountRawRow = {
  readonly count: number;
};

const EffectHashesSchema = z.array(z.string().min(1));

// ----- Public functions -----------------------------------------------------

/**
 * Insert a fresh run row in `status: "queued"`. The engine calls this
 * synchronously before dispatching `processor.run()` — per
 * [[wiki/invariants/EVERY_PROCESSOR_RUN_IS_LEDGERED]] §"Structural
 * enforcement" §1.
 *
 * INSERT (not OR IGNORE): the run id is a UUID-like generated by
 * `newRunId`, so a duplicate-id insert is a programmer error worth
 * raising as a SQLite UNIQUE-constraint exception rather than silently
 * dropping the row.
 */
export function insertQueued(db: LedgerDb, opts: InsertQueuedOpts): void {
  db.raw.query(INSERT_QUEUED_SQL).run(
    opts.id,
    opts.proposalId,
    opts.processorId,
    opts.processorVersion,
    opts.phase,
    opts.inputCommit,
    opts.triggerKind,
    JSON.stringify(opts.triggerPayload ?? null),
    opts.startedAt.toISOString(),
  );
}

/**
 * Transition a `queued` row to `running`. UPDATE filters by
 * `status = 'queued'` — a double-call (concurrent dispatcher race, or
 * the caller invoking out of order) is a no-op.
 *
 * The `now` parameter is currently unused on the SQL side (the spec's
 * `started_at` is the queue-time timestamp, not the running-time one),
 * but the caller still passes it so a future surface change (e.g.,
 * adding a `transitions_json` column with per-state timestamps) can use
 * it without a signature break.
 */
export function markRunning(db: LedgerDb, id: RunId, _now: Date): void {
  db.raw.query(MARK_RUNNING_SQL).run(id);
}

/**
 * Transition a `running` row to `succeeded`. Captures
 * `effect_hashes_json`, `cost_usd`, `duration_ms`, `output_commit`, and
 * `finished_at`. UPDATE filters by `status = 'running'` so a double-call
 * (or a call against a row in another state) is a no-op.
 *
 * `effectHashes` is JSON-encoded; an empty array (`[]`) is valid and
 * means the run emitted zero effects (a query-phase run, or an
 * adoption-phase run whose processor found nothing to do).
 */
export function markSucceeded(db: LedgerDb, opts: MarkSucceededOpts): void {
  db.raw.query(MARK_SUCCEEDED_SQL).run(
    JSON.stringify(opts.effectHashes),
    opts.costUsd,
    opts.durationMs,
    opts.outputCommit,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

/**
 * Transition a `running` row to `failed`. Captures `error`, `duration_ms`,
 * and `finished_at`. UPDATE filters by `status = 'running'` so a
 * double-call is a no-op.
 *
 * The executor-wired runtime calls this for failed terminal results:
 * thrown processors, invalid output, or other non-timeout/non-cancelled
 * execution failures. Structured executor errors are JSON-encoded here;
 * legacy string callers are still accepted for orphan recovery and tests.
 */
export function markFailed(db: LedgerDb, opts: MarkFailedOpts): void {
  const error =
    typeof opts.error === "string" ? opts.error : JSON.stringify(opts.error);
  db.raw.query(MARK_FAILED_SQL).run(
    error,
    opts.costUsd ?? null,
    opts.durationMs,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

export function markTimedOut(db: LedgerDb, opts: MarkTimedOutOpts): void {
  db.raw.query(MARK_TIMED_OUT_SQL).run(
    JSON.stringify(opts.error),
    opts.costUsd ?? null,
    opts.durationMs,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

export function markCancelled(db: LedgerDb, opts: MarkCancelledOpts): void {
  db.raw.query(MARK_CANCELLED_SQL).run(
    JSON.stringify(opts.error),
    opts.costUsd ?? null,
    opts.durationMs,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

/**
 * Transition a `queued` row to `skipped`. Used when a run is not invoked:
 * idempotency dedup may short-circuit a run before dispatch, execution
 * policy can deny a run before `markRunning`, and future quarantine can
 * suppress a matching trigger. Captures `finished_at` and, when supplied,
 * an `error`/reason string. Idempotency skips should continue omitting
 * `error`, preserving the historical NULL column value.
 *
 * `duration_ms` and `effect_hashes_json` remain at their queued-state
 * defaults (null / "[]") because processor code never ran.
 *
 * UPDATE filters by `status = 'queued'` so a call against an already-
 * transitioned row is a no-op.
 */
export function markSkipped(db: LedgerDb, opts: MarkSkippedOpts): void {
  db.raw.query(MARK_SKIPPED_SQL).run(
    opts.error ?? null,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

/**
 * Discriminated terminal-state dispatch over the running→terminal mark
 * functions. markSkipped is intentionally excluded (queued→skipped is not
 * a running-terminal).
 *
 * Compile-time exhaustiveness is enforced at the construction site: the
 * value-returning `toTerminalMark` switch in runtime.ts produces TS2366 if
 * a new status variant is added without a matching case. The `default` guard
 * below is a defence-in-depth catch for any unconstructed variant that
 * reaches the dispatch site without going through `toTerminalMark`.
 */
export type TerminalMark =
  | {
      readonly status: "succeeded";
      readonly effectHashes: ReadonlyArray<string>;
      readonly costUsd: number | null;
      readonly durationMs: number;
      readonly outputCommit: CommitOid | null;
    }
  | {
      readonly status: "failed";
      readonly error: string | ProcessorFailedExecutionError;
      readonly costUsd?: number | null;
      readonly durationMs: number;
    }
  | {
      readonly status: "timed_out";
      readonly error: ProcessorTimeoutExecutionError;
      readonly costUsd?: number | null;
      readonly durationMs: number;
    }
  | {
      readonly status: "cancelled";
      readonly error: ProcessorCancelledExecutionError;
      readonly costUsd?: number | null;
      readonly durationMs: number;
    };

export function markTerminal(
  db: LedgerDb,
  opts: TerminalMark & { readonly id: RunId; readonly finishedAt: Date },
): void {
  switch (opts.status) {
    case "succeeded":
      markSucceeded(db, opts);
      return;
    case "failed":
      markFailed(db, opts);
      return;
    case "timed_out":
      markTimedOut(db, opts);
      return;
    case "cancelled":
      markCancelled(db, opts);
      return;
    default: {
      const _exhaustive: never = opts;
      throw new Error(`unreachable terminal status: ${(_exhaustive as { status: string }).status}`);
    }
  }
}

/**
 * Land the closure-commit OID on the `output_commit` column of every named
 * successful run. Called by `src/engine/core/adopt.ts` after `makeClosureCommit`
 * returns a non-null OID for the iteration.
 *
 * The UPDATE filters by `status = 'succeeded' AND output_commit IS NULL`:
 * the run lifecycle is owned by `processor.run()` (per
 * [[wiki/invariants/EVERY_PROCESSOR_RUN_IS_LEDGERED]]); this accessor only
 * lands the trailer-join key after the fact. The IS-NULL guard means
 * calling twice is a no-op (second call updates zero rows) — useful if the
 * engine's adoption cycle were ever re-driven against the same runIds.
 *
 * Returns the number of rows updated. An empty `runIds` array short-
 * circuits to zero (no SQL is issued).
 *
 * See docs/wiki/gotchas/run-succeeded-before-closure.md for why this is a
 * separate write, not part of `markSucceeded`.
 */
export function updateOutputCommit(
  db: LedgerDb,
  opts: UpdateOutputCommitOpts,
): number {
  if (opts.runIds.length === 0) return 0;
  // SQLite has no array-binding for IN(); compose `?, ?, ...` placeholders
  // for the variable-length runIds set. The placeholders are followed by the
  // closing `)`; the leading `?` (the outputCommit value) is the first arg.
  const placeholders = opts.runIds.map(() => "?").join(", ");
  const sql = `${UPDATE_OUTPUT_COMMIT_SQL_PREFIX}${placeholders})`;
  const result = db.raw
    .query(sql)
    .run(opts.outputCommit, ...opts.runIds);
  return result.changes;
}

/**
 * Read every run matching the optional filter, ordered by `started_at`
 * descending (newest first — matches the `dome inspect runs`
 * expectation). Returns a frozen array.
 *
 * `limit`, if provided, caps the row count (the underlying SQL appends
 * `LIMIT ?`). Filters compose with AND.
 */
export function queryRuns(
  db: LedgerDb,
  filter?: RunsQueryFilter,
): ReadonlyArray<RunRow> {
  const { where, params } = runsWhereClause(filter);
  const sql = `${SELECT_BASE_SQL}${where} ORDER BY started_at DESC${limitClause(filter?.limit)}`;

  const rows = db.raw.query<RunRawRow, string[]>(sql).all(...params);
  return mapRows(rows, rowToRunRow);
}

/**
 * Read run metadata without deserializing the JSON payload columns.
 *
 * Use this for dashboards and health summaries that only need processor ids,
 * statuses, timestamps, and error text. `queryRuns` remains the strict full-row
 * accessor for detailed inspection surfaces.
 */
export function queryRunSummaries(
  db: LedgerDb,
  filter?: RunsQueryFilter,
): ReadonlyArray<RunSummaryRow> {
  const { where, params } = runsWhereClause(filter);
  const sql = `${SELECT_SUMMARY_BASE_SQL}${where} ORDER BY started_at DESC${limitClause(filter?.limit)}`;

  const rows = db.raw.query<RunSummaryRawRow, string[]>(sql).all(...params);
  return mapRows(rows, rowToRunSummaryRow);
}

export function countRuns(
  db: LedgerDb,
  filter?: RunsQueryFilter,
): number {
  const { where, params } = runsWhereClause(filter);
  const row = db.raw
    .query<CountRawRow, string[]>(`SELECT COUNT(*) AS count FROM runs${where}`)
    .get(...params);
  return row?.count ?? 0;
}

/**
 * Returns true when a terminal row should still route user/agent attention.
 *
 * Rows intentionally failed by the orphan-run recovery path are audit evidence
 * that a stuck run was resolved. They remain queryable through `inspect runs`,
 * but should not keep `status` / `check` in an unhealthy loop forever.
 */
export function isActiveProblemRun(
  row: Pick<RunRow, "status" | "error">,
): boolean {
  return ACTIVE_PROBLEM_RUN_STATUSES.has(row.status) &&
    !isRecoveredOrphanRun(row);
}

export function latestActiveProblemRuns(
  db: LedgerDb,
): ReadonlyArray<RunRow> {
  const rows = db.raw.query<RunRawRow, []>(LATEST_ACTIVE_PROBLEM_RUNS_SQL).all();
  return mapRows(rows, rowToRunRow);
}

export function countLatestActiveProblemRuns(db: LedgerDb): number {
  const row = db.raw
    .query<CountRawRow, []>(COUNT_LATEST_ACTIVE_PROBLEM_RUNS_SQL)
    .get();
  return row?.count ?? 0;
}

/**
 * Read a single run by id. Returns `null` if no row exists.
 */
export function getRun(db: LedgerDb, id: RunId): RunRow | null {
  const rows = db.raw.query<RunRawRow, [string]>(SELECT_BY_ID_SQL).all(id);
  const first = rows[0];
  if (first === undefined) return null;
  return rowToRunRow(first);
}

/**
 * Sum model costs for every processor in a bundle-prefix since a given
 * timestamp. The runtime passes the extension id as the prefix, so
 * `dome.agent` includes `dome.agent.ingest` and any sibling
 * processors while avoiding unrelated bundles.
 */
export function sumCostUsdByProcessorPrefix(
  db: LedgerDb,
  opts: SumCostUsdByProcessorPrefixOpts,
): number {
  const childPrefix = `${opts.processorIdPrefix}.`;
  const rows = db.raw
    .query<SumCostRawRow, [string, string, number, string]>(
      SUM_COST_USD_BY_PROCESSOR_PREFIX_SQL,
    )
    .all(
      opts.sinceIso,
      opts.processorIdPrefix,
      childPrefix.length,
      childPrefix,
    );
  const first = rows[0];
  return first?.cost_usd ?? 0;
}

/**
 * Per-processor spend aggregation over the report window — the query
 * surface behind `dome inspect cost`. Only cost-bearing rows participate
 * (same posture as `sumCostUsdByProcessorPrefix`): a NULL `cost_usd`
 * means the run never billed a provider. `todayCostUsd` re-splits the
 * same rows at `todayIso` so the report can show "since midnight" next
 * to the window total without a second query.
 */
export function aggregateCostUsdByProcessor(
  db: LedgerDb,
  opts: AggregateCostUsdByProcessorOpts,
): ReadonlyArray<ProcessorCostRow> {
  const rows = db.raw
    .query<ProcessorCostRawRow, [string, string]>(
      AGGREGATE_COST_USD_BY_PROCESSOR_SQL,
    )
    .all(opts.todayIso, opts.sinceIso);
  return mapRows(rows, (row) =>
    Object.freeze({
      processorId: row.processor_id,
      runs: row.runs,
      totalCostUsd: row.total_cost_usd,
      todayCostUsd: row.today_cost_usd,
    }),
  );
}

/**
 * Local-midnight boundary shared by every "today's spend" consumer: the
 * runtime's budget scopes and the `dome inspect cost` report must agree
 * on what "today" means, so the boundary lives beside the spend queries.
 */
export function startOfLocalDay(now: Date): Date {
  return new Date(now.getFullYear(), now.getMonth(), now.getDate());
}

const LATEST_SCHEDULE_RUN_SQL = `
SELECT started_at
FROM runs
WHERE processor_id = ? AND trigger_kind = 'schedule'
ORDER BY started_at DESC
LIMIT 1
`.trim();

/**
 * ISO-8601 `started_at` of the most recent schedule-triggered run for a
 * processor, or null when none is recorded. The scheduler uses this as the
 * durable fallback for a missing `schedule_cursors` row: projection state is
 * rebuildable by design, so a rebuild wipes cursors — without this fallback
 * every scheduled processor looks brand new after a rebuild and "new fires
 * on the first tick" re-fires (and re-charges) nightly LLM jobs on every
 * restart. Any recorded run counts as a fire regardless of terminal status:
 * a failed nightly run still consumed its slot (and possibly budget).
 */
export function latestScheduleRunStartedAt(
  db: LedgerDb,
  processorId: string,
): string | null {
  const rows = db.raw
    .query<{ started_at: string }, [string]>(LATEST_SCHEDULE_RUN_SQL)
    .all(processorId);
  return rows[0]?.started_at ?? null;
}

/**
 * Return every run currently in `status: 'running'` whose `started_at`
 * is older than `runningOlderThanMs` milliseconds before `now`. These are
 * candidates for the orphan-recovery path — they likely indicate an
 * engine crash between `markRunning` and a terminal mark.
 *
 * Wired to `dome inspect orphan-runs` (per spec §"Query surface
 * (CLI)" + §"Run lifecycle"). The returned array is frozen.
 */
/**
 * Processor-id prefixes the orphan-run RECOVERY path excludes from detection
 * to contain self-referential growth: the dome.health recovery processors run
 * on a minute cron and their own runs can go orphan, so detecting them would
 * mint a fresh "mark this orphan failed?" question about the detector itself
 * every minute. Inspection surfaces deliberately do NOT apply this, so a
 * genuinely stuck health run remains operator-visible.
 */
export const ORPHAN_RECOVERY_EXCLUDED_PROCESSOR_PREFIXES = Object.freeze([
  "dome.health.",
]);

export function orphanRuns(
  db: LedgerDb,
  runningOlderThanMs: number,
  now: Date,
  opts?: {
    /**
     * Processor-id prefixes to exclude. The RECOVERY surfaces pass
     * `["dome.health."]` so the orphan-run detector never raises a
     * self-referential question about its OWN minute-cadence runs (the
     * dome.health recovery processors are the machinery doing the detecting).
     * Raw callers (e.g. `dome inspect orphan-runs`) pass nothing, so a
     * genuinely stuck health run stays visible to an operator — the exclusion
     * narrows the auto-question path, it does not blind inspection.
     */
    readonly excludeProcessorIdPrefixes?: ReadonlyArray<string>;
  },
): ReadonlyArray<RunRow> {
  const cutoff = new Date(now.getTime() - runningOlderThanMs).toISOString();
  const rows = db.raw.query<RunRawRow, [string]>(ORPHAN_RUNS_SQL).all(cutoff);
  const mapped = mapRows(rows, rowToRunRow);
  const prefixes = opts?.excludeProcessorIdPrefixes ?? [];
  if (prefixes.length === 0) return mapped;
  return Object.freeze(
    mapped.filter(
      (row) => !prefixes.some((prefix) => row.processorId.startsWith(prefix)),
    ),
  );
}

/**
 * Transition every orphaned-`running` row (per `orphanRuns(...)`) to
 * `status: 'failed'`. Returns the count of rows transitioned. The
 * recovery path is retained for administrative/batch callers. The v1
 * question/answer path uses `failRunIfCurrent` instead so each user answer
 * targets one exact run generation.
 *
 * The synthetic error message identifies the recovery source so a future
 * `dome inspect` view can distinguish "real failure" from "engine crash
 * recovery." `finished_at` is set to `now` — the spec doesn't require
 * a per-row crash-time estimate.
 */
export function failOrphanedRuns(
  db: LedgerDb,
  runningOlderThanMs: number,
  now: Date,
): number {
  const cutoff = new Date(now.getTime() - runningOlderThanMs).toISOString();
  const result = db.raw
    .query(FAIL_ORPHANS_SQL)
    .run(now.toISOString(), cutoff);
  // Bun's sqlite returns a `Changes` object with `changes: number`.
  return result.changes;
}

/**
 * Transition one exact running-row generation to failed. The `started_at`
 * guard makes answer-mediated recovery stale-safe: a delayed answer cannot
 * mutate a row whose id/start generation no longer matches the question that
 * produced the RunRecoveryEffect.
 */
export function failRunIfCurrent(
  db: LedgerDb,
  opts: FailRunIfCurrentOpts,
): boolean {
  const result = db.raw.query(FAIL_RUN_IF_CURRENT_SQL).run(
    opts.error,
    durationBetween(opts.startedAt, opts.finishedAt),
    opts.finishedAt.toISOString(),
    opts.id,
    opts.startedAt,
    opts.processorId,
    opts.processorVersion,
    opts.phase,
  );
  return result.changes > 0;
}

// ----- internals ------------------------------------------------------------

// Row → RunRow / RunSummaryRow codecs are defined below, after the closed-enum
// arrays they reference (see `runCodec`). They deserialize JSON columns and
// narrow `status` / `phase` / `trigger_kind`, throwing on a value corrupted at
// the SQL boundary.

function runsWhereClause(
  filter?: RunsQueryFilter,
): { readonly where: string; readonly params: string[] } {
  const clauses: string[] = [];
  const params: string[] = [];

  if (filter?.processorId !== undefined) {
    clauses.push("processor_id = ?");
    params.push(filter.processorId);
  }
  if (filter?.phase !== undefined) {
    const phases = Array.isArray(filter.phase) ? filter.phase : [filter.phase];
    if (phases.length === 0) {
      clauses.push("0 = 1");
    } else {
      clauses.push(`phase IN (${phases.map(() => "?").join(", ")})`);
      params.push(...phases);
    }
  }
  if (filter?.status !== undefined) {
    clauses.push("status = ?");
    params.push(filter.status);
  }
  if (filter?.sinceIso !== undefined) {
    clauses.push("started_at >= ?");
    params.push(filter.sinceIso);
  }

  return Object.freeze({
    where: clauses.length === 0 ? "" : ` WHERE ${clauses.join(" AND ")}`,
    params,
  });
}

const RUN_STATUSES = [
  "queued",
  "running",
  "succeeded",
  "failed",
  "skipped",
  "timed_out",
  "cancelled",
] as const satisfies ReadonlyArray<RunStatus>;

const PROCESSOR_PHASES = [
  "adoption",
  "garden",
  "view",
] as const satisfies ReadonlyArray<ProcessorPhase>;

const TRIGGER_KINDS = [
  "signal",
  "path",
  "schedule",
  "answer",
  "command",
  "job",
] as const satisfies ReadonlyArray<TriggerKind>;

const runCodec = rowCodec<RunRawRow>("ledger.runs");

const rowToRunRow = runCodec.define<RunRow>({
  id: runCodec.brand("id", (v) => v as RunId),
  proposalId: runCodec.col("proposal_id"),
  processorId: runCodec.col("processor_id"),
  processorVersion: runCodec.col("processor_version"),
  phase: runCodec.enumCol("phase", PROCESSOR_PHASES),
  inputCommit: runCodec.brand("input_commit", commitOid),
  outputCommit: runCodec.nullableBrand("output_commit", commitOid),
  status: runCodec.enumCol("status", RUN_STATUSES),
  effectHashes: runCodec.jsonCol("effect_hashes_json", EffectHashesSchema),
  costUsd: runCodec.col("cost_usd"),
  durationMs: runCodec.col("duration_ms"),
  error: runCodec.col("error"),
  triggerKind: runCodec.enumCol("trigger_kind", TRIGGER_KINDS),
  // `custom`, not `jsonCol`: the trigger payload is left unfrozen (its shape is
  // opaque `unknown`), matching the hand-mapper that froze effectHashes but not
  // this column.
  triggerPayload: runCodec.custom((row) =>
    parseJsonColumn(
      row.trigger_payload_json,
      "ledger.runs.trigger_payload_json",
      JsonValueSchema,
    ),
  ),
  startedAt: runCodec.col("started_at"),
  finishedAt: runCodec.col("finished_at"),
});

// Bound to the narrower summary raw shape (`queryRunSummaries` SELECTs fewer
// columns), so the codec only reads columns that row actually carries.
const runSummaryCodec = rowCodec<RunSummaryRawRow>("ledger.runs");

const rowToRunSummaryRow = runSummaryCodec.define<RunSummaryRow>({
  id: runSummaryCodec.brand("id", (v) => v as RunId),
  processorId: runSummaryCodec.col("processor_id"),
  processorVersion: runSummaryCodec.col("processor_version"),
  phase: runSummaryCodec.enumCol("phase", PROCESSOR_PHASES),
  status: runSummaryCodec.enumCol("status", RUN_STATUSES),
  durationMs: runSummaryCodec.col("duration_ms"),
  error: runSummaryCodec.col("error"),
  triggerKind: runSummaryCodec.enumCol("trigger_kind", TRIGGER_KINDS),
  startedAt: runSummaryCodec.col("started_at"),
  finishedAt: runSummaryCodec.col("finished_at"),
});

function isRecoveredOrphanRun(
  row: Pick<RunRow, "status" | "error">,
): boolean {
  if (row.status !== "failed" || row.error === null) return false;
  return row.error.startsWith("orphaned-run:") ||
    row.error === "dome.health: mark orphaned processor run failed";
}

function durationBetween(startedAt: string, finishedAt: Date): number {
  const started = new Date(startedAt).getTime();
  if (Number.isNaN(started)) return 0;
  return Math.max(0, finishedAt.getTime() - started);
}
