// ledger-runs: the per-run lifecycle accessors for the `runs` table.
// Owns the run id generator, the run-status state transitions, the read
// surface (`queryRuns`, `getRun`), and the
// orphan-detection helpers used by `dome inspect orphan-runs` /
// `--orphan-runs --fail`.
//
// Normative references:
//   - docs/wiki/specs/run-ledger.md §"Tables — runs" (column shape +
//     status enum + run id format).
//   - docs/wiki/specs/run-ledger.md §"Run lifecycle" (the run states +
//     the engine-side write points: queued at enqueue, running at start
//     of Processor.run(), terminal at end; failed-run try/catch + orphan
//     detection on crash between running and terminal).
//   - docs/wiki/specs/run-ledger.md §"Query surface (CLI)" — the shape
//     of `dome inspect runs ...` queries.
//
// Structural fences this file upholds:
//   - docs/wiki/invariants/EVERY_PROCESSOR_RUN_IS_LEDGERED.md §"Structural
//     enforcement" — the engine writes `insertQueued` synchronously before
//     calling `processor.run()`, `markRunning` at the start of `run()`,
//     one terminal mark at the end. Crashes between
//     `markRunning` and the terminal mark leave rows visible to
//     `orphanRuns(...)`.
//
// Lifecycle invariants (the state machine this file encodes):
//
//   insertQueued        → row created, status="queued".
//
//   markRunning         → "queued" → "running". UPDATE filters by
//                         status="queued" so a double-mark is a no-op
//                         (concurrent dispatcher race protection).
//
//   markSucceeded       → "running" → "succeeded". Terminal. Captures
//                         effect_hashes_json, cost_usd, duration_ms,
//                         output_commit, finished_at. UPDATE filters
//                         by status="running".
//
//   markFailed          → "running" → "failed". Terminal. Captures
//                         error, duration_ms, finished_at. UPDATE filters
//                         by status="running".
//
//   markTimedOut        → "running" → "timed_out". Terminal. Captures
//                         structured error JSON, duration_ms, finished_at.
//                         UPDATE filters by status="running".
//
//   markCancelled       → "running" → "cancelled". Terminal. Captures
//                         structured error JSON, duration_ms, finished_at.
//                         UPDATE filters by status="running".
//
//   markSkipped         → "queued" → "skipped". Terminal. Captures
//                         finished_at and optionally error/reason JSON.
//                         UPDATE filters by status="queued". Used for
//                         any not-invoked run, including idempotency
//                         dedup and pre-run policy denial.
//
// `failOrphanedRuns` is the recovery path for engine crashes between
// `markRunning` and a terminal mark — it transitions stuck-running rows
// to `failed` so the audit history reaches a terminal state. v1.0
// surfaces orphans via `dome inspect runs --status running`; v1.x wires
// the recovery via the engine-asks model — the deferred
// `dome.health.detect-orphan-runs` garden-phase processor emits a
// QuestionEffect per orphan row, and the user answers `fail` / `keep`
// via `dome answer` (the answer-handler invokes `failOrphanedRuns`).
//
// Imports (tight by design — the ledger is the SQLite boundary):
//   - `node:crypto` for the random suffix in `newRunId`.
//   - `./db` for the `LedgerDb` handle.
//   - `../core/processor` for the `ProcessorPhase` type.
//   - `../core/source-ref` for the `CommitOid` brand + `commitOid` helper.
//   - `../engine/runner-contract` for the shared RunId and structured
//     execution-error type contracts.
//
// House-style notes (mirrors src/outbox/dispatch.ts, src/projections/jobs.ts):
//   - `type X = { ... }` aliases (not `interface`), every field `readonly`.
//   - JSON columns (`effect_hashes_json`, `trigger_payload_json`) serialized
//     via `JSON.stringify` on write, parsed on read.
//   - INSERT uses simple `INSERT` (no `OR IGNORE`): the `id` is a
//     UUID-like generated by `newRunId`, so collisions are practically
//     impossible. A duplicate-id INSERT will throw — that's a programmer
//     error worth surfacing, not a silent dedup.
//   - Returned arrays are `Object.freeze`'d.
//   - `noUncheckedIndexedAccess` discipline: row arrays are mapped
//     functionally; index access into `.all()` results checks `=== undefined`.

import { randomBytes } from "node:crypto";

import type { ProcessorPhase } from "../core/processor";
import { commitOid, type CommitOid } from "../core/source-ref";
import {
  type ProcessorCancelledExecutionError,
  type ProcessorFailedExecutionError,
  type ProcessorTimeoutExecutionError,
  type RunId,
} from "../engine/runner-contract";
import type { LedgerDb } from "./db";

// ----- Branded RunId --------------------------------------------------------
//
// The `RunId` brand is owned by `../engine/runner-contract` (the engine ↔
// runtime contract that the ledger consumes). Re-exported here so existing
// callers — `src/processors/runtime.ts`, the ledger accessors below — can
// keep importing it from the ledger surface unchanged.

export type { RunId };

// ----- Run lifecycle status -------------------------------------------------

/**
 * The closed set of lifecycle states per spec §"Run lifecycle".
 *
 * - `queued`    — engine enqueued the invocation; processor.run() not yet started.
 * - `running`   — processor.run() is executing.
 * - `succeeded` — processor.run() returned without throwing.
 * - `failed`    — processor.run() threw, or returned an invalid Effect, or
 *                 the orphan-recovery path transitioned a stuck-running row.
 * - `skipped`   — the run was not invoked (idempotency dedup, policy denial, etc.).
 * - `timed_out` — processor execution exceeded its configured deadline.
 * - `cancelled` — processor execution was cancelled by shutdown/re-drive.
 */
export type RunStatus =
  | "queued"
  | "running"
  | "succeeded"
  | "failed"
  | "skipped"
  | "timed_out"
  | "cancelled";

// ----- Trigger kind --------------------------------------------------------

/**
 * The trigger kinds per spec §"Tables — runs" `trigger_kind` column.
 * Mirrors the `kind` discriminator of `Trigger` in `src/core/processor.ts`;
 * stored as a plain string in SQLite (the full Trigger payload is captured
 * separately via `trigger_payload_json`).
 */
export type TriggerKind =
  | "signal"
  | "path"
  | "schedule"
  | "answer"
  | "command"
  | "job";

// ----- newRunId -------------------------------------------------------------

/**
 * Length of the random suffix in a RunId. Per spec: `<6-char-rand>`.
 * Six hex chars = 24 bits of entropy = ~16M values; within a single
 * millisecond bucket the collision probability is negligible.
 */
const RUN_ID_RAND_LEN = 6;

/**
 * Generate a fresh RunId in the canonical `run_<unix-ms>_<6-char-rand>`
 * format. The default `random` source uses `node:crypto.randomBytes` for
 * cryptographic-quality entropy; tests can pass a deterministic stub.
 *
 * The `random` parameter returns the raw 6-char-suffix string directly
 * (not bytes) — this keeps the test stub trivial (`() => "abcdef"`).
 */
export function newRunId(now: Date, random?: () => string): RunId {
  const rand = random === undefined ? defaultRandomSuffix() : random();
  return `run_${now.getTime()}_${rand}` as RunId;
}

function defaultRandomSuffix(): string {
  // 3 bytes = 6 hex chars; matches RUN_ID_RAND_LEN.
  return randomBytes(RUN_ID_RAND_LEN / 2).toString("hex");
}

// ----- Public types ---------------------------------------------------------

export type InsertQueuedOpts = {
  readonly id: RunId;
  readonly proposalId: string | null;
  readonly processorId: string;
  readonly processorVersion: string;
  readonly phase: ProcessorPhase;
  readonly inputCommit: CommitOid;
  readonly triggerKind: TriggerKind;
  /** JSON-serializable payload captured for audit (the input that fired the trigger). */
  readonly triggerPayload: unknown;
  readonly startedAt: Date;
};

export type MarkSucceededOpts = {
  readonly id: RunId;
  /** sha256s of each emitted effect; empty array is valid (no effects emitted). */
  readonly effectHashes: ReadonlyArray<string>;
  readonly costUsd: number | null;
  readonly durationMs: number;
  readonly outputCommit: CommitOid | null;
  readonly finishedAt: Date;
};

export type MarkFailedOpts = {
  readonly id: RunId;
  readonly error: string | ProcessorFailedExecutionError;
  readonly costUsd?: number | null;
  readonly durationMs: number;
  readonly finishedAt: Date;
};

export type MarkTimedOutOpts = {
  readonly id: RunId;
  readonly error: ProcessorTimeoutExecutionError;
  readonly costUsd?: number | null;
  readonly durationMs: number;
  readonly finishedAt: Date;
};

export type MarkCancelledOpts = {
  readonly id: RunId;
  readonly error: ProcessorCancelledExecutionError;
  readonly costUsd?: number | null;
  readonly durationMs: number;
  readonly finishedAt: Date;
};

export type MarkSkippedOpts = {
  readonly id: RunId;
  readonly finishedAt: Date;
  /**
   * Optional not-invoked reason. Idempotency skips usually leave this null;
   * policy denials and quarantine skips should write structured JSON.
   */
  readonly error?: string;
};

/**
 * Bulk-update `output_commit` for the named successful runs. Called by the
 * engine's adoption loop (`src/engine/adopt.ts`) once `makeClosureCommit`
 * returns a non-null OID — `markSucceeded` writes NULL into the column at
 * processor-run-terminal time (because the closure commit doesn't exist
 * yet), and this accessor lands the OID after the fact.
 *
 * The two-write pattern is intentional, NOT a layering bug — see
 * docs/wiki/gotchas/run-succeeded-before-closure.md. The run lifecycle is
 * bounded by `processor.run()`, not by the engine's adoption cycle; a run
 * whose effects were all rejected by the broker contributed nothing to the
 * closure commit and must still reach `succeeded`.
 */
export type UpdateOutputCommitOpts = {
  readonly runIds: ReadonlyArray<RunId>;
  readonly outputCommit: CommitOid;
};

/**
 * Row shape returned by `queryRuns` / `getRun` / `orphanRuns`. JSON columns
 * are deserialized. Nullable columns are typed `T | null` (not `T | undefined`)
 * so SQL NULL maps cleanly under `exactOptionalPropertyTypes`.
 */
export type RunRow = {
  readonly id: RunId;
  readonly proposalId: string | null;
  readonly processorId: string;
  readonly processorVersion: string;
  readonly phase: ProcessorPhase;
  readonly inputCommit: CommitOid;
  readonly outputCommit: CommitOid | null;
  readonly status: RunStatus;
  readonly effectHashes: ReadonlyArray<string>;
  readonly costUsd: number | null;
  readonly durationMs: number | null;
  readonly error: string | null;
  readonly triggerKind: TriggerKind;
  readonly triggerPayload: unknown;
  readonly startedAt: string;
  readonly finishedAt: string | null;
};

export type RunsQueryFilter = {
  readonly processorId?: string;
  readonly status?: RunStatus;
  /** ISO-8601 lower bound on `started_at`. */
  readonly sinceIso?: string;
  readonly limit?: number;
};

// ----- SQL ------------------------------------------------------------------

const INSERT_QUEUED_SQL = `
INSERT INTO runs (
  id, proposal_id, processor_id, processor_version, phase,
  input_commit, output_commit, status, effect_hashes_json,
  cost_usd, duration_ms, error, trigger_kind, trigger_payload_json,
  started_at, finished_at
) VALUES (?, ?, ?, ?, ?, ?, NULL, 'queued', '[]', NULL, NULL, NULL, ?, ?, ?, NULL)
`.trim();

const MARK_RUNNING_SQL = `
UPDATE runs
SET status = 'running'
WHERE id = ? AND status = 'queued'
`.trim();

const MARK_SUCCEEDED_SQL = `
UPDATE runs
SET status = 'succeeded',
    effect_hashes_json = ?,
    cost_usd = ?,
    duration_ms = ?,
    output_commit = ?,
    finished_at = ?
WHERE id = ? AND status = 'running'
`.trim();

const MARK_FAILED_SQL = `
UPDATE runs
SET status = 'failed',
    error = ?,
    cost_usd = ?,
    duration_ms = ?,
    finished_at = ?
WHERE id = ? AND status = 'running'
`.trim();

const MARK_TIMED_OUT_SQL = `
UPDATE runs
SET status = 'timed_out',
    error = ?,
    cost_usd = ?,
    duration_ms = ?,
    finished_at = ?
WHERE id = ? AND status = 'running'
`.trim();

const MARK_CANCELLED_SQL = `
UPDATE runs
SET status = 'cancelled',
    error = ?,
    cost_usd = ?,
    duration_ms = ?,
    finished_at = ?
WHERE id = ? AND status = 'running'
`.trim();

const MARK_SKIPPED_SQL = `
UPDATE runs
SET status = 'skipped',
    error = ?,
    finished_at = ?
WHERE id = ? AND status = 'queued'
`.trim();

// `updateOutputCommit` is parameterized per-call because the `IN (...)` set
// is variable-length; the SQL template is composed inline. Filters by
// `status = 'succeeded' AND output_commit IS NULL` so the OID lands at most
// once per run (defense against a re-driven adoption loop replaying the
// same runIds against a different closure commit).
const UPDATE_OUTPUT_COMMIT_SQL_PREFIX = `
UPDATE runs
SET output_commit = ?
WHERE status = 'succeeded' AND output_commit IS NULL AND id IN (
`.trim();

const SELECT_BASE_SQL = `
SELECT id, proposal_id, processor_id, processor_version, phase,
       input_commit, output_commit, status, effect_hashes_json,
       cost_usd, duration_ms, error, trigger_kind, trigger_payload_json,
       started_at, finished_at
FROM runs
`.trim();

const SELECT_BY_ID_SQL = `${SELECT_BASE_SQL} WHERE id = ?`;

const ORPHAN_RUNS_SQL = `
${SELECT_BASE_SQL}
WHERE status = 'running' AND started_at < ?
ORDER BY started_at
`.trim();

const FAIL_ORPHANS_SQL = `
UPDATE runs
SET status = 'failed',
    error = 'orphaned-run: engine crash detected; transitioned by failOrphanedRuns',
    finished_at = ?
WHERE status = 'running' AND started_at < ?
`.trim();

// ----- Raw row shape --------------------------------------------------------

type RunRawRow = {
  readonly id: string;
  readonly proposal_id: string | null;
  readonly processor_id: string;
  readonly processor_version: string;
  readonly phase: string;
  readonly input_commit: string;
  readonly output_commit: string | null;
  readonly status: string;
  readonly effect_hashes_json: string;
  readonly cost_usd: number | null;
  readonly duration_ms: number | null;
  readonly error: string | null;
  readonly trigger_kind: string;
  readonly trigger_payload_json: string;
  readonly started_at: string;
  readonly finished_at: string | null;
};

// ----- Public functions -----------------------------------------------------

/**
 * Insert a fresh run row in `status: "queued"`. The engine calls this
 * synchronously before dispatching `processor.run()` — per
 * [[wiki/invariants/EVERY_PROCESSOR_RUN_IS_LEDGERED]] §"Structural
 * enforcement" §1.
 *
 * INSERT (not OR IGNORE): the run id is a UUID-like generated by
 * `newRunId`, so a duplicate-id insert is a programmer error worth
 * raising as a SQLite UNIQUE-constraint exception rather than silently
 * dropping the row.
 */
export function insertQueued(db: LedgerDb, opts: InsertQueuedOpts): void {
  db.raw.query(INSERT_QUEUED_SQL).run(
    opts.id,
    opts.proposalId,
    opts.processorId,
    opts.processorVersion,
    opts.phase,
    opts.inputCommit,
    opts.triggerKind,
    JSON.stringify(opts.triggerPayload ?? null),
    opts.startedAt.toISOString(),
  );
}

/**
 * Transition a `queued` row to `running`. UPDATE filters by
 * `status = 'queued'` — a double-call (concurrent dispatcher race, or
 * the caller invoking out of order) is a no-op.
 *
 * The `now` parameter is currently unused on the SQL side (the spec's
 * `started_at` is the queue-time timestamp, not the running-time one),
 * but the caller still passes it so a future surface change (e.g.,
 * adding a `transitions_json` column with per-state timestamps) can use
 * it without a signature break.
 */
export function markRunning(db: LedgerDb, id: RunId, _now: Date): void {
  db.raw.query(MARK_RUNNING_SQL).run(id);
}

/**
 * Transition a `running` row to `succeeded`. Captures
 * `effect_hashes_json`, `cost_usd`, `duration_ms`, `output_commit`, and
 * `finished_at`. UPDATE filters by `status = 'running'` so a double-call
 * (or a call against a row in another state) is a no-op.
 *
 * `effectHashes` is JSON-encoded; an empty array (`[]`) is valid and
 * means the run emitted zero effects (a query-phase run, or an
 * adoption-phase run whose processor found nothing to do).
 */
export function markSucceeded(db: LedgerDb, opts: MarkSucceededOpts): void {
  db.raw.query(MARK_SUCCEEDED_SQL).run(
    JSON.stringify(opts.effectHashes),
    opts.costUsd,
    opts.durationMs,
    opts.outputCommit,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

/**
 * Transition a `running` row to `failed`. Captures `error`, `duration_ms`,
 * and `finished_at`. UPDATE filters by `status = 'running'` so a
 * double-call is a no-op.
 *
 * The executor-wired runtime calls this for failed terminal results:
 * thrown processors, invalid output, or other non-timeout/non-cancelled
 * execution failures. Structured executor errors are JSON-encoded here;
 * legacy string callers are still accepted for orphan recovery and tests.
 */
export function markFailed(db: LedgerDb, opts: MarkFailedOpts): void {
  const error =
    typeof opts.error === "string" ? opts.error : JSON.stringify(opts.error);
  db.raw.query(MARK_FAILED_SQL).run(
    error,
    opts.costUsd ?? null,
    opts.durationMs,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

export function markTimedOut(db: LedgerDb, opts: MarkTimedOutOpts): void {
  db.raw.query(MARK_TIMED_OUT_SQL).run(
    JSON.stringify(opts.error),
    opts.costUsd ?? null,
    opts.durationMs,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

export function markCancelled(db: LedgerDb, opts: MarkCancelledOpts): void {
  db.raw.query(MARK_CANCELLED_SQL).run(
    JSON.stringify(opts.error),
    opts.costUsd ?? null,
    opts.durationMs,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

/**
 * Transition a `queued` row to `skipped`. Used when a run is not invoked:
 * idempotency dedup may short-circuit a run before dispatch, execution
 * policy can deny a run before `markRunning`, and future quarantine can
 * suppress a matching trigger. Captures `finished_at` and, when supplied,
 * an `error`/reason string. Idempotency skips should continue omitting
 * `error`, preserving the historical NULL column value.
 *
 * `duration_ms` and `effect_hashes_json` remain at their queued-state
 * defaults (null / "[]") because processor code never ran.
 *
 * UPDATE filters by `status = 'queued'` so a call against an already-
 * transitioned row is a no-op.
 */
export function markSkipped(db: LedgerDb, opts: MarkSkippedOpts): void {
  db.raw.query(MARK_SKIPPED_SQL).run(
    opts.error ?? null,
    opts.finishedAt.toISOString(),
    opts.id,
  );
}

/**
 * Land the closure-commit OID on the `output_commit` column of every named
 * successful run. Called by `src/engine/adopt.ts` after `makeClosureCommit`
 * returns a non-null OID for the iteration.
 *
 * The UPDATE filters by `status = 'succeeded' AND output_commit IS NULL`:
 * the run lifecycle is owned by `processor.run()` (per
 * [[wiki/invariants/EVERY_PROCESSOR_RUN_IS_LEDGERED]]); this accessor only
 * lands the trailer-join key after the fact. The IS-NULL guard means
 * calling twice is a no-op (second call updates zero rows) — useful if the
 * engine's adoption cycle were ever re-driven against the same runIds.
 *
 * Returns the number of rows updated. An empty `runIds` array short-
 * circuits to zero (no SQL is issued).
 *
 * See docs/wiki/gotchas/run-succeeded-before-closure.md for why this is a
 * separate write, not part of `markSucceeded`.
 */
export function updateOutputCommit(
  db: LedgerDb,
  opts: UpdateOutputCommitOpts,
): number {
  if (opts.runIds.length === 0) return 0;
  // SQLite has no array-binding for IN(); compose `?, ?, ...` placeholders
  // for the variable-length runIds set. The placeholders are followed by the
  // closing `)`; the leading `?` (the outputCommit value) is the first arg.
  const placeholders = opts.runIds.map(() => "?").join(", ");
  const sql = `${UPDATE_OUTPUT_COMMIT_SQL_PREFIX}${placeholders})`;
  const result = db.raw
    .query(sql)
    .run(opts.outputCommit, ...opts.runIds);
  return result.changes;
}

/**
 * Read every run matching the optional filter, ordered by `started_at`
 * descending (newest first — matches the `dome inspect runs`
 * expectation). Returns a frozen array.
 *
 * `limit`, if provided, caps the row count (the underlying SQL appends
 * `LIMIT ?`). Filters compose with AND.
 */
export function queryRuns(
  db: LedgerDb,
  filter?: RunsQueryFilter,
): ReadonlyArray<RunRow> {
  const clauses: string[] = [];
  const params: string[] = [];

  if (filter?.processorId !== undefined) {
    clauses.push("processor_id = ?");
    params.push(filter.processorId);
  }
  if (filter?.status !== undefined) {
    clauses.push("status = ?");
    params.push(filter.status);
  }
  if (filter?.sinceIso !== undefined) {
    clauses.push("started_at >= ?");
    params.push(filter.sinceIso);
  }

  const where = clauses.length === 0 ? "" : ` WHERE ${clauses.join(" AND ")}`;
  // `limit` is interpolated (not parameterized) because SQLite doesn't allow
  // `?` placeholders in the LIMIT clause in older PRAGMA modes; `Math.floor`
  // bounds it to an integer to prevent SQL-injection-via-NaN.
  const limitClause =
    filter?.limit !== undefined ? ` LIMIT ${Math.floor(filter.limit)}` : "";
  const sql = `${SELECT_BASE_SQL}${where} ORDER BY started_at DESC${limitClause}`;

  const rows = db.raw.query<RunRawRow, string[]>(sql).all(...params);
  return Object.freeze(rows.map(rowToRunRow));
}

/**
 * Read a single run by id. Returns `null` if no row exists.
 */
export function getRun(db: LedgerDb, id: RunId): RunRow | null {
  const rows = db.raw.query<RunRawRow, [string]>(SELECT_BY_ID_SQL).all(id);
  const first = rows[0];
  if (first === undefined) return null;
  return rowToRunRow(first);
}

/**
 * Return every run currently in `status: 'running'` whose `started_at`
 * is older than `runningOlderThanMs` milliseconds before `now`. These are
 * candidates for the orphan-recovery path — they likely indicate an
 * engine crash between `markRunning` and a terminal mark.
 *
 * Wired to `dome inspect orphan-runs` (per spec §"Query surface
 * (CLI)" + §"Run lifecycle"). The returned array is frozen.
 */
export function orphanRuns(
  db: LedgerDb,
  runningOlderThanMs: number,
  now: Date,
): ReadonlyArray<RunRow> {
  const cutoff = new Date(now.getTime() - runningOlderThanMs).toISOString();
  const rows = db.raw.query<RunRawRow, [string]>(ORPHAN_RUNS_SQL).all(cutoff);
  return Object.freeze(rows.map(rowToRunRow));
}

/**
 * Transition every orphaned-`running` row (per `orphanRuns(...)`) to
 * `status: 'failed'`. Returns the count of rows transitioned. The
 * recovery path is the engine-asks flow per [[wiki/specs/cli]] §"dome
 * answer" — the deferred `dome.health.detect-orphan-runs` garden-phase
 * processor emits a `QuestionEffect` per orphan row; the user answers
 * `fail` via `dome answer <id>`; the answer-handler invokes this.
 *
 * The synthetic error message identifies the recovery source so a future
 * `dome inspect` view can distinguish "real failure" from "engine crash
 * recovery." `finished_at` is set to `now` — the spec doesn't require
 * a per-row crash-time estimate.
 */
export function failOrphanedRuns(
  db: LedgerDb,
  runningOlderThanMs: number,
  now: Date,
): number {
  const cutoff = new Date(now.getTime() - runningOlderThanMs).toISOString();
  const result = db.raw
    .query(FAIL_ORPHANS_SQL)
    .run(now.toISOString(), cutoff);
  // Bun's sqlite returns a `Changes` object with `changes: number`.
  return result.changes;
}

// ----- internals ------------------------------------------------------------

/**
 * Row → RunRow. Deserializes JSON columns and narrows the `status`,
 * `phase`, `trigger_kind` strings to their closed unions. Throws on an
 * unrecognized value (a row corrupted at the SQL boundary — programmer
 * error or external tampering with the db file).
 */
function rowToRunRow(row: RunRawRow): RunRow {
  return Object.freeze({
    id: row.id as RunId,
    proposalId: row.proposal_id,
    processorId: row.processor_id,
    processorVersion: row.processor_version,
    phase: narrowPhase(row.phase),
    inputCommit: commitOid(row.input_commit),
    outputCommit: row.output_commit === null ? null : commitOid(row.output_commit),
    status: narrowStatus(row.status),
    effectHashes: Object.freeze(
      JSON.parse(row.effect_hashes_json) as ReadonlyArray<string>,
    ),
    costUsd: row.cost_usd,
    durationMs: row.duration_ms,
    error: row.error,
    triggerKind: narrowTriggerKind(row.trigger_kind),
    triggerPayload: JSON.parse(row.trigger_payload_json) as unknown,
    startedAt: row.started_at,
    finishedAt: row.finished_at,
  });
}

function narrowStatus(s: string): RunStatus {
  switch (s) {
    case "queued":
    case "running":
    case "succeeded":
    case "failed":
    case "skipped":
    case "timed_out":
    case "cancelled":
      return s;
    default:
      throw new Error(`ledger.runs: unknown status '${s}'`);
  }
}

function narrowPhase(s: string): ProcessorPhase {
  switch (s) {
    case "adoption":
    case "garden":
    case "view":
      return s;
    default:
      throw new Error(`ledger.runs: unknown phase '${s}'`);
  }
}

function narrowTriggerKind(s: string): TriggerKind {
  switch (s) {
    case "signal":
    case "path":
    case "schedule":
    case "answer":
    case "command":
    case "job":
      return s;
    default:
      throw new Error(`ledger.runs: unknown trigger_kind '${s}'`);
  }
}
