import { NewContentMessage } from '@dome/common';

/**
 * Environment bindings for the AI Processor service
 * Extends the global Env interface from worker-configuration.d.ts
 */
export interface Env extends globalThis.Env {
  // Queue bindings with specific types
  NEW_CONTENT: Queue<NewContentMessage>;
  ENRICHED_CONTENT: Queue<EnrichedContentMessage>;
  
  // Service bindings with specific types
  SILO: SiloBinding;
}

/**
 * Silo service binding interface
 */
export interface SiloBinding {
  batchGet(data: { ids: string[]; userId?: string | null }): Promise<SiloBatchGetResponse>;
}

/**
 * Silo batch get response
 */
export interface SiloBatchGetResponse {
  items: SiloBatchGetItem[];
  total: number;
  limit: number;
  offset: number;
}

/**
 * Silo batch get item
 */
export interface SiloBatchGetItem {
  id: string;
  userId: string | null;
  contentType: string;
  size: number;
  createdAt: number;
  body?: string;
  url?: string;
}

/**
 * Enriched content message sent to the ENRICHED_CONTENT queue
 */
export interface EnrichedContentMessage {
  id: string;
  userId: string | null;
  contentType: string;
  metadata: EnrichedMetadata;
  timestamp: number;
}

/**
 * Enriched metadata generated by the LLM
 */
export interface EnrichedMetadata {
  title?: string;
  summary?: string;
  todos?: Todo[];
  reminders?: Reminder[];
  topics?: string[];
  sentiment?: 'positive' | 'neutral' | 'negative';
  processingVersion: number;
  modelUsed: string;
}

/**
 * Todo item extracted from content
 */
export interface Todo {
  text: string;
  dueDate?: string; // ISO date if detected
  priority?: 'high' | 'medium' | 'low';
}

/**
 * Reminder item extracted from content
 */
export interface Reminder {
  text: string;
  reminderTime?: string; // ISO date if detected
}

/**
 * Message batch from queue
 */
export interface MessageBatch<T> {
  queue: string;
  messages: { id: string; body: T; timestamp: number }[];
}