/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const BulkReprocessBody: core.serialization.Schema<serializers.BulkReprocessBody.Raw, DomeApi.BulkReprocessBody>;
export declare namespace BulkReprocessBody {
    interface Raw {
        contentIds: string[];
    }
}
