/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostChatRequestOptions: core.serialization.ObjectSchema<
    serializers.PostChatRequestOptions.Raw,
    DomeApi.PostChatRequestOptions
> = core.serialization.object({
    enhanceWithContext: core.serialization.boolean().optional(),
    maxContextItems: core.serialization.number().optional(),
    includeSourceInfo: core.serialization.boolean().optional(),
    maxTokens: core.serialization.number().optional(),
    temperature: core.serialization.number().optional(),
    modelId: core.serialization.string().optional(),
});

export declare namespace PostChatRequestOptions {
    export interface Raw {
        enhanceWithContext?: boolean | null;
        maxContextItems?: number | null;
        includeSourceInfo?: boolean | null;
        maxTokens?: number | null;
        temperature?: number | null;
        modelId?: string | null;
    }
}
