/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";
import { PostChatRequestMessagesItemRole } from "./PostChatRequestMessagesItemRole";

export const PostChatRequestMessagesItem: core.serialization.ObjectSchema<
    serializers.PostChatRequestMessagesItem.Raw,
    DomeApi.PostChatRequestMessagesItem
> = core.serialization.object({
    role: PostChatRequestMessagesItemRole,
    content: core.serialization.string(),
    timestamp: core.serialization.number().optional(),
});

export declare namespace PostChatRequestMessagesItem {
    export interface Raw {
        role: PostChatRequestMessagesItemRole.Raw;
        content: string;
        timestamp?: number | null;
    }
}
