/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostChatRequestMessagesItemRole: core.serialization.Schema<
    serializers.PostChatRequestMessagesItemRole.Raw,
    DomeApi.PostChatRequestMessagesItemRole
> = core.serialization.enum_(["user", "assistant", "system"]);

export declare namespace PostChatRequestMessagesItemRole {
    export type Raw = "user" | "assistant" | "system";
}
