/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 7b3093fc4664c329037d4d700aaf2891)
// Runtime types generated with workerd@1.20250416.0 2023-12-01 nodejs_compat
declare namespace Cloudflare {
  interface Env {
    LOG_LEVEL: 'info' | 'debug';
    VERSION: '0.1.0';
    ENVIRONMENT: 'dev' | 'staging' | 'prod';
    SILO: Fetcher;
    ENRICHED_CONTENT: Queue;
    REMINDER_QUEUE: Queue;
    AI: Ai;
  }
}
interface Env extends Cloudflare.Env {}
