name = "ai-processor"
main = "src/index.ts"
workers_dev = false   # <-- no public *.workers.dev URL
compatibility_date = "2025-04-15"
compatibility_flags = ["nodejs_compat"]

# Queue consumer for NEW_CONTENT
[[queues.consumers]]
queue = "new-content-ai"
binding = "NEW_CONTENT"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3

# Queue producer for ENRICHED_CONTENT
[[queues.producers]]
queue = "enriched-content"
binding = "ENRICHED_CONTENT"

# Queue producer for TODOS
[[queues.producers]]
queue = "todos"
binding = "TODOS"

# Rate limit DLQ for handling rate-limited AI requests
[[queues.producers]]
queue = "rate-limit-dlq"
binding = "RATE_LIMIT_DLQ"

# Rate limit DLQ consumer
[[queues.consumers]]
queue = "rate-limit-dlq"
binding = "RATE_LIMIT_DLQ"
max_batch_size = 5  # Smaller batch size for rate-limited content
max_batch_timeout = 30  # Longer timeout to avoid overwhelming the AI service
max_retries = 10  # More retries for rate-limited content
dead_letter_queue = "ingest-dlq"  # Send to general DLQ after all retries exhaust

# AI binding for Workers AI
[ai]
binding = "AI"

# Binding to Silo service for content fetching
[[services]]
binding = "SILO"
service = "silo"

[vars]
LOG_LEVEL = "info"
VERSION = "0.1.0"
ENVIRONMENT = "dev"

# Dev environment
[env.dev]
name = "ai-processor-dev"
[env.dev.vars]
LOG_LEVEL = "debug"
ENVIRONMENT = "dev"

# Staging environment
[env.staging]
name = "ai-processor-staging"
[env.staging.vars]
LOG_LEVEL = "info"
ENVIRONMENT = "staging"

# Production environment
[env.prod]
name = "ai-processor"
[env.prod.vars]
LOG_LEVEL = "info"
ENVIRONMENT = "prod"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
