/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";

export const IngestNoteBodyApiSchemaCategory: core.serialization.Schema<
    serializers.IngestNoteBodyApiSchemaCategory.Raw,
    DomeApi.IngestNoteBodyApiSchemaCategory
> = core.serialization.enum_(["note", "code", "document", "article", "other"]);

export declare namespace IngestNoteBodyApiSchemaCategory {
    export type Raw = "note" | "code" | "document" | "article" | "other";
}
