name = "github-ingestor"
main = "src/index.ts"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_als"]

# Trigger the worker every hour as fallback
[triggers]
crons = ["0 * * * *"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "github-ingestor"
database_id = "08d66bbb-c86c-40d3-8df3-1d9902fc52f4"

# Service bindings
[[services]]
binding = "SILO"
service = "silo"
environment = "production"

# Queues
[[queues.producers]]
binding = "INGEST_QUEUE"
queue = "ingest-queue"

[[queues.consumers]]
binding = "INGEST_QUEUE"
queue = "ingest-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 5

[[queues.producers]]
binding = "DEAD_LETTER_QUEUE"
queue = "ingest-dead-letter"

# Environment variables
[vars]
LOG_LEVEL = "info"
VERSION = "1.0.0"
ENVIRONMENT = "prod"

# Development environment variables
[env.dev]
name = "github-ingestor-dev"
[env.dev.vars]
LOG_LEVEL = "debug"
ENVIRONMENT = "dev"

# Staging environment variables
[env.staging]
name = "github-ingestor-staging"
[env.staging.vars]
LOG_LEVEL = "info"
ENVIRONMENT = "staging"

[observability]
enabled = true
head_sampling_rate = 1
