name = "rust-worker-template"
compatibility_date = "2023-04-15"

# For Rust workers, we don't specify a main JS/TS file
# Instead, we configure the build process

[build]
command = "cargo build --release --target wasm32-unknown-unknown"
# The output_path should point to the compiled WebAssembly file
output_path = "target/wasm32-unknown-unknown/release/rust_worker.wasm"

[vars]
ENVIRONMENT = "development"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }