/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DomeApi from "../../../../index";
/**
 * @example
 *     {
 *         limit: 50,
 *         offset: 0
 *     }
 */
export interface GetNotesRequest {
    limit?: number;
    offset?: number;
    category?: DomeApi.GetNotesRequestCategory;
}
