/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const RegisterGithubRepoBody: core.serialization.Schema<
    serializers.RegisterGithubRepoBody.Raw,
    DomeApi.RegisterGithubRepoBody
> = core.serialization.object({
    owner: core.serialization.string(),
    repo: core.serialization.string(),
});

export declare namespace RegisterGithubRepoBody {
    export interface Raw {
        owner: string;
        repo: string;
    }
}
