/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const PostChatRequestMessagesItemRole: core.serialization.Schema<serializers.PostChatRequestMessagesItemRole.Raw, DomeApi.PostChatRequestMessagesItemRole>;
export declare namespace PostChatRequestMessagesItemRole {
    type Raw = "user" | "assistant" | "system";
}
