/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const IngestNoteBodyApiSchemaCategory: core.serialization.Schema<serializers.IngestNoteBodyApiSchemaCategory.Raw, DomeApi.IngestNoteBodyApiSchemaCategory>;
export declare namespace IngestNoteBodyApiSchemaCategory {
    type Raw = "note" | "code" | "document" | "article" | "other";
}
