/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { PostChatRequestMessagesItem } from "../../types/PostChatRequestMessagesItem";
import { PostChatRequestOptions } from "../../types/PostChatRequestOptions";
export declare const PostChatRequest: core.serialization.Schema<serializers.PostChatRequest.Raw, DomeApi.PostChatRequest>;
export declare namespace PostChatRequest {
    interface Raw {
        stream?: boolean | null;
        userId: string;
        messages: PostChatRequestMessagesItem.Raw[];
        options: PostChatRequestOptions.Raw;
        runId?: string | null;
    }
}
