/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type GetNotesRequestCategory = "note" | "code" | "document" | "article" | "other";
export declare const GetNotesRequestCategory: {
    readonly Note: "note";
    readonly Code: "code";
    readonly Document: "document";
    readonly Article: "article";
    readonly Other: "other";
};
