/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Defaults to 'note' if not provided
 */
export type IngestNoteBodyApiSchemaCategory = "note" | "code" | "document" | "article" | "other";
export declare const IngestNoteBodyApiSchemaCategory: {
    readonly Note: "note";
    readonly Code: "code";
    readonly Document: "document";
    readonly Article: "article";
    readonly Other: "other";
};
