/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../../../../index";

/**
 * @example
 *     {
 *         content: "Content for the new note."
 *     }
 */
export interface IngestNoteBodyApiSchema {
    title?: string;
    content: string;
    /** Defaults to 'note' if not provided */
    category?: DomeApi.IngestNoteBodyApiSchemaCategory;
    /** Defaults to 'text/markdown' if not provided */
    mimeType?: DomeApi.IngestNoteBodyApiSchemaMimeType;
}
