"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DomeApiClient = void 0;
const Client_1 = require("./api/resources/auth/client/Client");
const Client_2 = require("./api/resources/public/client/Client");
const Client_3 = require("./api/resources/chat/client/Client");
const Client_4 = require("./api/resources/notes/client/Client");
const Client_5 = require("./api/resources/search/client/Client");
const Client_6 = require("./api/resources/contentGitHub/client/Client");
const Client_7 = require("./api/resources/contentSync/client/Client");
const Client_8 = require("./api/resources/contentNotion/client/Client");
const Client_9 = require("./api/resources/ai/client/Client");
class DomeApiClient {
    constructor(_options) {
        this._options = _options;
    }
    get auth() {
        var _a;
        return ((_a = this._auth) !== null && _a !== void 0 ? _a : (this._auth = new Client_1.Auth(this._options)));
    }
    get public() {
        var _a;
        return ((_a = this._public) !== null && _a !== void 0 ? _a : (this._public = new Client_2.Public(this._options)));
    }
    get chat() {
        var _a;
        return ((_a = this._chat) !== null && _a !== void 0 ? _a : (this._chat = new Client_3.Chat(this._options)));
    }
    get notes() {
        var _a;
        return ((_a = this._notes) !== null && _a !== void 0 ? _a : (this._notes = new Client_4.Notes(this._options)));
    }
    get search() {
        var _a;
        return ((_a = this._search) !== null && _a !== void 0 ? _a : (this._search = new Client_5.Search(this._options)));
    }
    get contentGitHub() {
        var _a;
        return ((_a = this._contentGitHub) !== null && _a !== void 0 ? _a : (this._contentGitHub = new Client_6.ContentGitHub(this._options)));
    }
    get contentSync() {
        var _a;
        return ((_a = this._contentSync) !== null && _a !== void 0 ? _a : (this._contentSync = new Client_7.ContentSync(this._options)));
    }
    get contentNotion() {
        var _a;
        return ((_a = this._contentNotion) !== null && _a !== void 0 ? _a : (this._contentNotion = new Client_8.ContentNotion(this._options)));
    }
    get ai() {
        var _a;
        return ((_a = this._ai) !== null && _a !== void 0 ? _a : (this._ai = new Client_9.Ai(this._options)));
    }
}
exports.DomeApiClient = DomeApiClient;
