/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ConfigureNotionOAuthBody {
    clientId?: string;
    clientSecret?: string;
    redirectUri?: string;
}
