/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as DomeApi from "../../../index";
export declare namespace ContentGitHub {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class ContentGitHub {
    protected readonly _options: ContentGitHub.Options;
    constructor(_options: ContentGitHub.Options);
    /**
     * @param {DomeApi.RegisterGithubRepoBody} request
     * @param {ContentGitHub.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link DomeApi.BadRequestError}
     * @throws {@link DomeApi.UnauthorizedError}
     * @throws {@link DomeApi.InternalServerError}
     *
     * @example
     *     await client.contentGitHub.registerGitHubRepository({
     *         owner: "my-org",
     *         repo: "my-repo"
     *     })
     */
    registerGitHubRepository(request: DomeApi.RegisterGithubRepoBody, requestOptions?: ContentGitHub.RequestOptions): Promise<DomeApi.GithubRepoResponse>;
    /**
     * @param {string} owner
     * @param {string} repo
     * @param {ContentGitHub.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link DomeApi.UnauthorizedError}
     * @throws {@link DomeApi.NotFoundError}
     * @throws {@link DomeApi.InternalServerError}
     *
     * @example
     *     await client.contentGitHub.getGitHubRepositorySyncHistory("my-org", "my-repo")
     */
    getGitHubRepositorySyncHistory(owner: string, repo: string, requestOptions?: ContentGitHub.RequestOptions): Promise<DomeApi.SyncHistoryResponse>;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
