/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const RegisterBody: core.serialization.Schema<serializers.RegisterBody.Raw, DomeApi.RegisterBody>;
export declare namespace RegisterBody {
    interface Raw {
        email: string;
        password: string;
        name: string;
    }
}
