#!/usr/bin/env bun

import { homedir } from "node:os";
import { resolve } from "node:path";

type JsonRecord = Record<string, unknown>;

type SnapshotOptions = {
  readonly vault: string;
  readonly topic: string;
  readonly date: string;
  readonly limit: number;
};

type CommandRun = {
  readonly args: ReadonlyArray<string>;
};

const repoRoot = resolve(import.meta.dir, "..");

async function main(): Promise<void> {
  const args = Bun.argv.slice(2);
  if (args.includes("-h") || args.includes("--help")) {
    nodeWrite(helpText());
    return;
  }

  const opts = parseArgs(args);
  const commands: CommandRun[] = [];

  const status = await domeJson<JsonRecord>(commands, [
    "status",
    "--vault",
    opts.vault,
    "--json",
  ]);
  const check = await domeJson<JsonRecord>(commands, [
    "check",
    "--vault",
    opts.vault,
    "--json",
  ]);
  const query = await domeJson<JsonRecord>(commands, [
    "query",
    "--vault",
    opts.vault,
    opts.topic,
    "--limit",
    String(opts.limit),
    "--json",
  ]);
  const exportContext = await domeJson<JsonRecord>(commands, [
    "export-context",
    "--vault",
    opts.vault,
    opts.topic,
    "--limit",
    String(opts.limit),
    "--json",
  ]);

  nodeWrite(renderSnapshot({
    opts,
    commands,
    status,
    check,
    query,
    exportContext,
  }));
}

function renderSnapshot(input: {
  readonly opts: SnapshotOptions;
  readonly commands: ReadonlyArray<CommandRun>;
  readonly status: JsonRecord;
  readonly check: JsonRecord;
  readonly query: JsonRecord;
  readonly exportContext: JsonRecord;
}): string {
  const lines: string[] = [];
  const { opts } = input;

  lines.push(`## ${opts.date} Dogfood Snapshot`);
  lines.push("");
  lines.push("Generated by `bun run v1:dogfood-snapshot`.");
  lines.push("");
  lines.push("Commands run:");
  for (const command of input.commands) {
    lines.push(
      `- \`bin/dome ${command.args.map(formatCommandArg).join(" ")}\``,
    );
  }

  lines.push("");
  lines.push("Operational state:");
  lines.push(
    `- Vault: \`${stringValue(input.status.vault, opts.vault)}\` on branch ` +
      `\`${stringValue(input.status.branch, "(unknown)")}\``,
  );
  lines.push(
    `- Head/adopted: \`${shortOid(input.status.head)}\` / ` +
      `\`${shortOid(input.status.adopted)}\`; sync needed: ` +
      `${yesNo(input.status.sync_needed)}`,
  );
  lines.push(
    `- Dirty files: ${numberValue(input.status.dirty_modified)} modified, ` +
      `${numberValue(input.status.dirty_untracked)} untracked`,
  );
  lines.push(
    `- Operational runs: ${numberValue(input.status.pending_runs)} pending, ` +
      `${numberValue(input.status.failed_runs)} failed, ` +
      `${numberValue(input.status.outbox_failed)} failed outbox, ` +
      `${numberValue(input.status.quarantined)} quarantined`,
  );
  lines.push(
    `- Serve host: ${formatServeStatus(input.status)}`,
  );
  lines.push(
    `- Attention: ${yesNo(input.status.attention_required)}; diagnostics: ` +
      `${numberValue(input.status.diagnostics)} total / ` +
      `${numberValue(input.status.attention_diagnostics)} attention; ` +
      `questions: ${numberValue(input.status.questions)}`,
  );

  const loops = recordArray(input.status.maintenance_loops);
  if (loops.length > 0) {
    lines.push("");
    lines.push("Maintenance loops:");
    for (const loop of loops) {
      lines.push(formatLoopSummary(loop));
      lines.push(`  - processors: ${formatLoopProcessors(loop)}`);
      const missing = stringArray(loop.missing_processors);
      if (missing.length > 0) {
        lines.push(`  - missing: ${formatBoundedList(missing)}`);
      }
      const inactiveOptional = stringArray(loop.inactive_optional_processors);
      if (inactiveOptional.length > 0) {
        lines.push(
          `  - inactive optional: ${formatBoundedList(inactiveOptional)}`,
        );
      }
      const surfaces = stringArray(loop.surfaces);
      if (surfaces.length > 0) {
        lines.push(`  - surfaces: ${surfaces.join(", ")}`);
      }
      const settlement = record(loop.settlement);
      const noOp = stringValue(settlement.no_op_when, "");
      if (noOp !== "") {
        lines.push(`  - no-op: ${trimOneLine(noOp)}`);
      }
    }
  }

  const content = record(input.check.content);
  const dispositionSummary = record(content.disposition_summary);
  const dispositionGroups = recordArray(dispositionSummary.groups);
  const repairSummary = record(content.repair_summary);
  const repairGroups = recordArray(repairSummary.groups);
  const contentItems = recordArray(content.items);
  if (dispositionGroups.length > 0 || repairGroups.length > 0) {
    lines.push("");
    lines.push("Content hygiene:");
    for (const group of dispositionGroups.slice(0, 5)) {
      lines.push(
        `- ${stringValue(group.disposition, "(unknown)")}: ` +
          `${numberValue(group.count)} finding(s), ` +
          `${numberValue(group.attention_count)} attention`,
      );
    }
    for (const group of repairGroups.slice(0, 5)) {
      lines.push(
        `- ${stringValue(group.repair_path, "(unknown)")}: ` +
          `${numberValue(group.count)} finding(s), ` +
          `${numberValue(group.attention_count)} attention`,
      );
    }
    if (contentItems.length > 0) {
      lines.push("- Example findings:");
      for (const item of contentItems.slice(0, 5)) {
        lines.push(
          `  - ${stringValue(item.severity, "unknown")} ` +
            `${stringValue(item.code, "unknown")}: ` +
            `${trimOneLine(stringValue(item.message, "(missing message)"))} ` +
            `(${formatDiagnosticLocation(item)})`,
        );
      }
    }
  }

  const overview = record(input.exportContext.overview);
  const readFirst = recordArray(overview.readFirst);
  const packetLoops = recordArray(overview.openLoops);
  lines.push("");
  lines.push("Work surface:");
  lines.push(
    `- Topic: \`${opts.topic}\`; read-first entries: ${readFirst.length}; ` +
      `open-loop examples: ${packetLoops.length}`,
  );
  if (packetLoops.length > 0) {
    lines.push("- Open-loop examples:");
    for (const item of packetLoops.slice(0, 5)) {
      lines.push(
        `  - ${trimOneLine(stringValue(item.text, "(missing text)"))} ` +
          `(${stringValue(item.path, "(unknown)")})`,
      );
    }
  }

  lines.push("");
  lines.push(`Context packet: \`${opts.topic}\``);
  lines.push(
    `- Entries shown: ${numberValue(record(input.exportContext.shown).entries)}; ` +
      `has more: ${yesNo(record(input.exportContext.hasMore).entries)}`,
  );
  if (readFirst.length > 0) {
    lines.push("- Read first:");
    for (const item of readFirst.slice(0, 5)) {
      lines.push(
        `  - \`${stringValue(item.path, "(unknown)")}\` - ` +
          trimOneLine(stringValue(item.reason, "")),
      );
    }
  }
  const matches = recordArray(input.query.matches);
  if (matches.length > 0) {
    lines.push("");
    lines.push("Query top matches:");
    for (const match of matches.slice(0, 5)) {
      const ranking = record(match.ranking);
      const reasons = stringArray(ranking.reasons).join("; ");
      lines.push(
        `- \`${stringValue(match.path, "(unknown)")}\` - ` +
          (reasons === "" ? "no ranking reason" : reasons),
      );
    }
  }

  lines.push("");
  lines.push("Qualitative notes to fill after the work session:");
  lines.push("- Daily note usefulness:");
  lines.push("- Capture digestion:");
  lines.push("- Open-loop surfacing:");
  lines.push("- Context packet quality:");
  lines.push("- Question burden:");
  lines.push("- Link/concept hygiene:");
  lines.push("- Friction / manual foreground-agent work Dome should own:");
  lines.push("- Lost or overwritten human markdown edits:");
  lines.push("- Manual .dome/state edits:");
  lines.push("");
  lines.push(
    "M10 status: this snapshot is supporting evidence only; elapsed real " +
      "work-vault use is still required before V1 is done.",
  );
  lines.push("");
  return `${lines.join("\n")}\n`;
}

async function domeJson<T>(
  commands: CommandRun[],
  args: ReadonlyArray<string>,
): Promise<T> {
  commands.push({ args });
  const proc = Bun.spawn({
    cmd: [resolve(repoRoot, "bin", "dome"), ...args],
    cwd: repoRoot,
    stdout: "pipe",
    stderr: "pipe",
    timeout: 20_000,
    killSignal: "SIGKILL",
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (exitCode !== 0) {
    throw new Error(
      `bin/dome ${args.join(" ")} exited ${exitCode}${formatStderr(stderr)}`,
    );
  }
  try {
    return JSON.parse(stdout) as T;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(
      `bin/dome ${args.join(" ")} returned non-JSON stdout: ${message}`,
    );
  }
}

function record(value: unknown): JsonRecord {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }
  return value as JsonRecord;
}

function recordArray(value: unknown): JsonRecord[] {
  if (!Array.isArray(value)) return [];
  return value.map((item) => record(item));
}

function stringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is string => typeof item === "string");
}

function stringValue(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim() !== "" ? value : fallback;
}

function numberValue(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) ? value : 0;
}

function yesNo(value: unknown): string {
  return value === true ? "yes" : "no";
}

function shortOid(value: unknown): string {
  if (typeof value !== "string" || value.length === 0) return "(none)";
  return value.slice(0, 7);
}

function trimOneLine(value: string): string {
  const collapsed = value.replace(/\s+/g, " ").trim();
  return collapsed.length <= 180 ? collapsed : `${collapsed.slice(0, 177)}...`;
}

function formatPathLine(path: unknown, line: unknown): string {
  const renderedPath = stringValue(path, "(unknown)");
  const renderedLine = numberValue(line);
  return renderedLine > 0 ? `${renderedPath}:${renderedLine}` : renderedPath;
}

function formatDiagnosticLocation(item: JsonRecord): string {
  const sourceRefs = stringValue(item.source_refs, "");
  if (sourceRefs !== "") return sourceRefs;
  const refs = recordArray(item.sourceRefs);
  const first = refs[0];
  if (first === undefined) return "(unknown)";
  const range = record(first.range);
  return formatPathLine(first.path, range.startLine);
}

function formatServeStatus(status: JsonRecord): string {
  const serveStatus = stringValue(status.serve_status, "unknown");
  if (serveStatus === "off") return "off";
  const parts = [serveStatus];
  const branch = stringValue(status.serve_branch, "");
  if (branch !== "") parts.push(`branch ${branch}`);
  const pid = numberValue(status.serve_pid);
  if (pid > 0) parts.push(`pid ${pid}`);
  const updatedAt = stringValue(status.serve_updated_at, "");
  if (updatedAt !== "") parts.push(`updated ${updatedAt}`);
  return parts.join("; ");
}

function formatLoopSummary(loop: JsonRecord): string {
  const id = stringValue(loop.id, "(unknown)");
  const state = stringValue(loop.state, "(unknown)");
  const attentionDiagnostics = numberValue(loop.attention_diagnostics);
  const driftDiagnostics = numberValue(loop.drift_diagnostics);
  const questions = numberValue(loop.questions);
  const agentSafe = numberValue(loop.agent_safe_questions);
  const modelSafe = numberValue(loop.model_safe_questions);
  const ownerNeeded = numberValue(loop.owner_needed_questions);
  const problemRuns = numberValue(loop.recent_problem_runs);
  const latestRun = stringValue(loop.latest_run_at, "(none)");
  const lastSuccess = stringValue(loop.last_successful_run_at, "(none)");
  const latestProblem = stringValue(loop.latest_problem_run_at, "");
  const questionCounts =
    `${agentSafe} agent-safe, ${modelSafe} model-safe, ${ownerNeeded} owner-needed`;
  const parts = [
    `- \`${id}\`: ${state}`,
    `diagnostics ${attentionDiagnostics} attention / ${driftDiagnostics} drift`,
    `questions ${questions} (${questionCounts})`,
    `problem runs ${problemRuns}`,
    `latest run ${latestRun}`,
    `last success ${lastSuccess}`,
  ];
  if (latestProblem !== "") parts.push(`latest problem ${latestProblem}`);
  return parts.join("; ");
}

function formatLoopProcessors(loop: JsonRecord): string {
  const active = stringArray(loop.active_processors).length;
  const total = stringArray(loop.processor_ids).length;
  const required = stringArray(loop.required_processor_ids).length;
  const missing = stringArray(loop.missing_processors).length;
  const inactiveOptional = stringArray(loop.inactive_optional_processors).length;
  const parts = [`${active}/${total} active`, `${required} required`];
  if (missing > 0) parts.push(`${missing} missing`);
  if (inactiveOptional > 0) parts.push(`${inactiveOptional} inactive optional`);
  return parts.join(", ");
}

function formatBoundedList(values: ReadonlyArray<string>): string {
  const maxShown = 3;
  const shown = values.slice(0, maxShown);
  const remaining = values.length - shown.length;
  if (remaining <= 0) return shown.join(", ");
  return `${shown.join(", ")}, +${remaining} more`;
}

function formatStderr(stderr: string): string {
  const trimmed = stderr.trim();
  return trimmed === "" ? "" : `: ${trimmed}`;
}

function formatCommandArg(value: string): string {
  return /^[A-Za-z0-9_@%+=:,./~-]+$/.test(value)
    ? value
    : JSON.stringify(value);
}

function parseArgs(args: ReadonlyArray<string>): SnapshotOptions {
  let vault = resolve(homedir(), "vaults", "work");
  let topic = "today open loops";
  let date = localDateString();
  let limit = 8;

  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === "--vault") {
      vault = readValue(args, i, arg);
      i += 1;
      continue;
    }
    if (arg === "--topic") {
      topic = readValue(args, i, arg);
      i += 1;
      continue;
    }
    if (arg === "--date") {
      date = readValue(args, i, arg);
      i += 1;
      continue;
    }
    if (arg === "--limit") {
      limit = parsePositiveInteger(readValue(args, i, arg), arg);
      i += 1;
      continue;
    }
    if (arg === "-h" || arg === "--help") {
      throw new Error(`${arg} must be handled before parsing`);
    }
    throw new Error(`unknown argument: ${arg}`);
  }

  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    throw new Error("--date must use YYYY-MM-DD");
  }

  return Object.freeze({ vault, topic, date, limit });
}

function readValue(
  args: ReadonlyArray<string>,
  index: number,
  name: string,
): string {
  const value = args[index + 1];
  if (value === undefined || value.startsWith("--")) {
    throw new Error(`${name} requires a value`);
  }
  return value;
}

function parsePositiveInteger(value: string, name: string): number {
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed) || parsed <= 0) {
    throw new Error(`${name} must be a positive integer`);
  }
  return parsed;
}

function localDateString(now: Date = new Date()): string {
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function helpText(): string {
  return [
    "Usage: bun scripts/v1-dogfood-snapshot.ts [options]",
    "",
    "Emits a read-only Markdown snapshot for the M10 work-vault dogfood ledger.",
    "",
    "Options:",
    "  --vault <path>       Vault path (default: ~/vaults/work).",
    "  --topic <text>       Query/export-context topic (default: today open loops).",
    "  --date <YYYY-MM-DD>  Snapshot date (default: today).",
    "  --limit <n>          Query/export-context limit (default: 8).",
    "  -h, --help           Show this help.",
    "",
  ].join("\n");
}

function nodeWrite(text: string): void {
  process.stdout.write(text);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`v1-dogfood-snapshot: ${message}`);
  process.exit(1);
});
