/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const RegisterNotionWorkspaceBody: core.serialization.Schema<serializers.RegisterNotionWorkspaceBody.Raw, DomeApi.RegisterNotionWorkspaceBody>;
export declare namespace RegisterNotionWorkspaceBody {
    interface Raw {
        botId?: string | null;
        accessToken?: string | null;
        workspaceName?: string | null;
    }
}
