/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const RegisterNotionWorkspaceBody: core.serialization.Schema<
    serializers.RegisterNotionWorkspaceBody.Raw,
    DomeApi.RegisterNotionWorkspaceBody
> = core.serialization.object({
    botId: core.serialization.string().optional(),
    accessToken: core.serialization.string().optional(),
    workspaceName: core.serialization.string().optional(),
});

export declare namespace RegisterNotionWorkspaceBody {
    export interface Raw {
        botId?: string | null;
        accessToken?: string | null;
        workspaceName?: string | null;
    }
}
