/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const StoreNotionIntegrationBody: core.serialization.Schema<serializers.StoreNotionIntegrationBody.Raw, DomeApi.StoreNotionIntegrationBody>;
export declare namespace StoreNotionIntegrationBody {
    interface Raw {
        code: string;
        state?: string | null;
    }
}
