/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NoteCategory = "note" | "code" | "document" | "article" | "other";
export const NoteCategory = {
    Note: "note",
    Code: "code",
    Document: "document",
    Article: "article",
    Other: "other",
} as const;
