/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type NoteMimeType = "text/plain" | "text/markdown" | "text/html" | "application/json" | "application/javascript" | "application/python" | "application/pdf" | "image/jpeg" | "image/png" | string;
