/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../index";

export interface Note {
    id: string;
    userId?: string;
    category: DomeApi.NoteCategory;
    title?: string;
    content?: string;
    mimeType: DomeApi.NoteMimeType;
    size: number;
    createdAt: Date;
    /** URL for large content */
    url?: string;
    /** Custom metadata */
    customMetadata?: Record<string, unknown>;
}
