/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DomeApi from "../index";
export interface RootResponse {
    message: string;
    service: DomeApi.RootResponseService;
    description: string;
}
