/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../index";

export interface SearchResponse {
    success: boolean;
    results: DomeApi.SearchResultItem[];
    pagination: DomeApi.Pagination;
    query: string;
    message?: string;
}
