/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DomeApi from "../index";

export type StreamingSearchEvent =
    | DomeApi.StreamingSearchEvent.Metadata
    | DomeApi.StreamingSearchEvent.Result
    | DomeApi.StreamingSearchEvent.Error_;

export namespace StreamingSearchEvent {
    export interface Metadata extends DomeApi.StreamingMetadata {
        type: "metadata";
    }

    export interface Result extends DomeApi.StreamingResultData {
        type: "result";
    }

    export interface Error_ extends DomeApi.StreamingErrorData {
        type: "error";
    }
}
