// cli/commands/recipe: `dome recipe <kind>` — client setup recipes.
//
// v1 ships two recipes:
//   - `ios` — the iOS Shortcut that voice-captures into POST /capture (the
//     WS3-capture deliverable of the v1 plan).
//   - `core-seed` — the owner interview prompt that seeds core.md's two
//     owner-authored sections in one foreground session (WS1 of the v1
//     plan: core.md activation).
// Recipes are plain text by design: they change when the surfaces they
// describe change, so they live next to the CLI rather than in docs that
// can drift.

import { EX_USAGE } from "../exit-codes";

export type RecipeOptions = {
  readonly kind: string;
  /** Base URL of the dome http server (default http://<your-server>:3663). */
  readonly url?: string | undefined;
};

export async function runRecipe(options: RecipeOptions): Promise<number> {
  if (options.kind === "ios") {
    const base = (options.url ?? "http://<your-server>:3663")
      .replace(/\/+$/, "");
    console.log(iosRecipe(base));
    return 0;
  }
  if (options.kind === "core-seed") {
    console.log(coreSeedRecipe());
    return 0;
  }
  console.error(
    `dome recipe: unknown recipe '${options.kind}' (available: ios, core-seed)`,
  );
  return EX_USAGE;
}

function iosRecipe(base: string): string {
  return `dome recipe: iOS voice capture → ${base}/capture

Prerequisites
  1. The dome http surface is running on your server:
       DOME_HTTP_TOKEN=<token> dome http --vault <vault> --host <tailscale-ip>
     (bind a Tailscale interface, never a public one — see
      docs/wiki/specs/http-surface.md "Trust domain")
  2. Your phone is on the same Tailscale network.

Build the Shortcut (Shortcuts app → + → rename to "Dome Capture")
  1. Add action: "Dictate Text"
  2. Add action: "Get Contents of URL"
       URL:     ${base}/capture
       Method:  POST
       Headers: Authorization → Bearer <token>
       Request Body: JSON
         text      → Dictated Text   (the variable from step 1)
         captureId → Shortcut Input? No — add a "UUID" action before this
                     step and bind captureId → UUID (makes retries idempotent)
  3. Add action: "Show Notification" → "Captured ✓"
  4. (Optional) Settings → Action Button → assign "Dome Capture".
     The same Shortcut works from the Apple Watch Shortcuts complication.

Verify from any shell on the Tailscale network
  curl -s -X POST ${base}/capture \\
    -H "Authorization: Bearer <token>" \\
    -H "content-type: application/json" \\
    -d '{"text":"recipe smoke test","captureId":"recipe-test-1"}'
  → {"status":"captured", ...}   (compile_pending until the daemon adopts)

The cockpit
  Open ${base}/today?token=<token> on any device in the trust domain for the
  self-refreshing today view (add it to the iPhone home screen via Safari →
  Share → Add to Home Screen).
`;
}

function coreSeedRecipe(): string {
  return `dome recipe: core-seed — seed core.md, the always-loaded core memory page

core.md has three sections:
  ## Who I am              — owner-authored: role, team, context
  ## Active projects       — generated by Dome from open loops; do not hand-author
  ## Standing preferences  — owner-authored rules + a Dome-managed promoted block

Seed it in one foreground session: open your vault in Claude Code (or any
agent harness) and paste the prompt below. Review the draft, edit it until
it sounds like you, and commit.

--- paste below this line ---

Interview me to seed core.md, my always-loaded core memory page. Ask one
question at a time:

  1. Who am I? My role, what I'm responsible for, the context an agent
     should always have.
  2. Who is on my team / who do I work with most, and on what?
  3. What standing preferences should agents always honor — formatting,
     filing, naming, scope, tone?
  4. What am I currently focused on? (context for the draft only)

Then draft ONLY the "## Who I am" and "## Standing preferences" sections of
core.md and show them to me for my edit and approval before writing the
file. Rules:

  - Keep the whole page under the 6,000-character budget: always-relevant
    summary here, details in wiki pages.
  - NEVER write inside marker-delimited blocks (HTML-comment markers);
    they are Dome-managed — leave the markers and their contents alone.
  - "## Active projects" is generated by Dome — do not hand-author it;
    leave the heading empty.

--- paste above this line ---
`;
}
