// cli/commands/recipe: `dome recipe <kind>` — client setup recipes.
//
// v1 ships two recipes:
//   - `ios` — the iOS Shortcut that voice-captures into POST /capture (the
//     WS3-capture deliverable of the v1 plan).
//   - `core-seed` — the owner interview prompt that seeds core.md's two
//     owner-authored sections in one foreground session (WS1 of the v1
//     plan: core.md activation).
// Recipes are plain text by design: they change when the surfaces they
// describe change, so they live next to the CLI rather than in docs that
// can drift.

import { EX_USAGE } from "../exit-codes";

export type RecipeOptions = {
  readonly kind: string;
  /** Base URL of the dome http server (default http://<your-server>:3663). */
  readonly url?: string | undefined;
};

export async function runRecipe(options: RecipeOptions): Promise<number> {
  if (options.kind === "ios") {
    const base = (options.url ?? "http://<your-server>:3663")
      .replace(/\/+$/, "");
    console.log(iosRecipe(base));
    return 0;
  }
  if (options.kind === "core-seed") {
    console.log(coreSeedRecipe());
    return 0;
  }
  console.error(
    `dome recipe: unknown recipe '${options.kind}' (available: ios, core-seed)`,
  );
  return EX_USAGE;
}

function iosRecipe(base: string): string {
  return `dome recipe: iOS voice capture → ${base}/capture

Prerequisites
  1. The dome http surface is running on your server:
       DOME_HTTP_TOKEN=<token> dome http --vault <vault> --host <tailscale-ip>
     (bind a Tailscale interface, never a public one — see
      docs/wiki/specs/http-surface.md "Trust domain")
  2. Your phone is on the same Tailscale network.
  3. (Queue fallback) A "DomeCaptures" folder in iCloud Drive, drained on
     the laptop by \`dome recipe capture-queue\` — captures survive the
     host being asleep or unreachable.

Build the Shortcut (Shortcuts app → + → rename to "Dome Capture")
  1. Add action: "Dictate Text"
  2. Add action: "UUID"
  3. Add action: "Format Date"
       Date: Current Date, Date Format: Custom → yyyy-MM-dd-HHmmss
  4. Add action: "Text" → [Formatted Date]-[UUID]
     (the capture id — ONE string shared by the POST body and the queue
      filename, so a retry through either channel dedupes to one capture)
  5. Add action: "Save File"
       File: Dictated Text       Service: iCloud Drive
       Ask Where to Save: Off    Destination Path: DomeCaptures/[Text].md
     (queue first. Shortcuts has no try/catch: when "Get Contents of URL"
      hits an unreachable host it STOPS the shortcut — that stop is the
      failure branch, and the file saved here is what survives it. If
      "Save File" only offers the iCloud Drive/Shortcuts folder, create
      DomeCaptures inside it and point the drain there — see
      \`dome recipe capture-queue\` step 2.)
  6. Add action: "Get Contents of URL"
       URL:     ${base}/capture
       Method:  POST
       Headers: Authorization → Bearer <token>
       Request Body: JSON
         text      → Dictated Text   (the variable from step 1)
         captureId → Text            (the variable from step 4)
  7. Add action: "Delete Files" → File (from "Save File"),
       Confirm Before Deleting: Off
     (the POST landed, so the queue entry is cleared. If step 6 failed,
      the shortcut already stopped and the file waits in DomeCaptures/
      for the laptop-side drain — eventually consistent, never lost.)
  8. Add action: "Show Notification" → "Captured ✓"
  9. (Optional) Settings → Action Button → assign "Dome Capture".
     The same Shortcut works from the Apple Watch Shortcuts complication.

Verify from any shell on the Tailscale network
  curl -s -X POST ${base}/capture \\
    -H "Authorization: Bearer <token>" \\
    -H "content-type: application/json" \\
    -d '{"text":"recipe smoke test","captureId":"recipe-test-1"}'
  → {"status":"captured", ...}   (compile_pending until the daemon adopts)

The cockpit
  Open ${base}/today?token=<token> on any device in the trust domain for the
  self-refreshing today view (add it to the iPhone home screen via Safari →
  Share → Add to Home Screen).
`;
}

function coreSeedRecipe(): string {
  return `dome recipe: core-seed — seed core.md, the always-loaded core memory page

core.md has three sections:
  ## Who I am              — owner-authored: role, team, context
  ## Active projects       — generated by Dome from open loops; do not hand-author
  ## Standing preferences  — owner-authored rules + a Dome-managed promoted block

Seed it in one foreground session: open your vault in Claude Code (or any
agent harness) and paste the prompt below. Review the draft, edit it until
it sounds like you, and commit.

--- paste below this line ---

Interview me to seed core.md, my always-loaded core memory page. Ask one
question at a time:

  1. Who am I? My role, what I'm responsible for, the context an agent
     should always have.
  2. Who is on my team / who do I work with most, and on what?
  3. What standing preferences should agents always honor — formatting,
     filing, naming, scope, tone?
  4. What am I currently focused on? (context for the draft only)

Then draft ONLY the "## Who I am" and "## Standing preferences" sections of
core.md and show them to me for my edit and approval before writing the
file. Rules:

  - Keep the whole page under the 6,000-character budget: always-relevant
    summary here, details in wiki pages.
  - NEVER write inside marker-delimited blocks (HTML-comment markers);
    they are Dome-managed — leave the markers and their contents alone.
  - "## Active projects" is generated by Dome — do not hand-author it;
    leave the heading empty.

--- paste above this line ---
`;
}
