-- Migration: Create checkpoints table
-- Description: Sets up the initial schema for the chat orchestrator checkpointing
-- Generated by Drizzle ORM

CREATE TABLE `checkpoints` (
  `run_id` text PRIMARY KEY NOT NULL,
  `step` text NOT NULL,
  `state_json` text NOT NULL,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL,
  `user_id` text
);

-- Create index for efficient cleanup
CREATE INDEX `idx_checkpoints_updated_at` ON `checkpoints` (`updated_at`);

-- Create index for user-based filtering
CREATE INDEX `idx_checkpoints_user_id` ON `checkpoints` (`user_id`);