/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as DomeApi from "../index";
import * as core from "../../core";

export class ConflictError extends errors.DomeApiError {
    constructor(body: DomeApi.ErrorResponse, rawResponse?: core.RawResponse) {
        super({
            message: "ConflictError",
            statusCode: 409,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, ConflictError.prototype);
    }
}
