/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const LoginBody: core.serialization.Schema<serializers.LoginBody.Raw, DomeApi.LoginBody>;
export declare namespace LoginBody {
    interface Raw {
        email: string;
        password: string;
    }
}
