/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DomeApi from "../../../../api/index";
import * as core from "../../../../core";
import { Note } from "../../../types/Note";

export const Response: core.serialization.Schema<serializers.notes.listNotes.Response.Raw, DomeApi.Note[]> =
    core.serialization.list(Note);

export declare namespace Response {
    export type Raw = Note.Raw[];
}
