/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         owner: "my-org",
 *         repo: "my-repo"
 *     }
 */
export interface RegisterGithubRepoBody {
    owner: string;
    repo: string;
}
