// AGENTS.md content shape per docs/wiki/invariants/AGENTS_MD_IS_ORIENTATION_SURFACE.md.
// The file at vault root carries two sections: a templated section (generated
// from the vault's current config / page types / workflows; regenerated by
// `dome doctor --repair`) and a user-prose section (delimited by HTML comments;
// preserved verbatim across every --repair call).

import type { VaultConfig, PageTypesConfig } from "./vault";
import { INVARIANTS } from "./types";

export const USER_PROSE_BEGIN = "<!-- BEGIN user-prose -->";
export const USER_PROSE_END = "<!-- END user-prose -->";

/**
 * Generate the templated section of AGENTS.md from the vault's current state.
 * Carries: a one-line orientation header, the enabled invariant set, the
 * declared page-type defaults, and the shipped/active workflow names.
 */
export function buildAgentsMdTemplated(
  config: VaultConfig,
  pageTypes: PageTypesConfig,
  workflowNames: ReadonlyArray<string>,
): string {
  // Enumerate the full canonical invariant set so AGENTS.md reflects the
  // system's actual enforcement surface (axioms + shipped-default config +
  // opt-in flags), not just the subset flipped on in this vault's config.
  // Per AGENTS_MD_IS_ORIENTATION_SURFACE: the orientation surface must
  // teach the agent the vault's invariant set, not the runtime config slice.
  void config; // kept in the signature for backwards-compatible callers
  const allInvariants = Object.values(INVARIANTS).sort();

  const allPageTypes = [
    ...pageTypes.defaults,
    ...pageTypes.extensions.map(e => typeof e === "string" ? e : e.name),
  ];

  const workflows = [...workflowNames].sort();

  return `# This vault

A Dome vault. Operate against the markdown directly; the compiler daemon
(\`dome serve\`) catches your writes and reconciles the vault state. For
explicit operations, use the CLI: \`dome lint\`, \`dome lint --apply <id>\`,
\`dome doctor\`, \`dome export-context\`.

Offline rule surface: when you can't reach this README, the canonical
substrate lives at \`docs/wiki/invariants/\` and \`docs/wiki/specs/\`.

## Conventions

- Markdown is the source of truth. Anything Dome derives can be rebuilt from
  the markdown alone.
- Write to \`wiki/<type>/<name>.md\` for typed wiki pages; never to \`raw/\`
  (immutable); never directly mutate \`log.md\` or \`index.md\`.
- Wikilinks use full paths: \`[[wiki/entities/x]]\` not \`[[x]]\`.
- Page type comes from directory: \`wiki/entities/\` is type \`entity\`, etc.

## Enabled invariants

${allInvariants.map(n => `- \`${n}\``).join("\n")}

See \`docs/wiki/invariants/\` for the canonical definitions.

## Page types

${allPageTypes.map(t => `- \`${t}\``).join("\n")}

## Workflows

${workflows.map(w => `- \`${w}\` — invoke via \`dome ${w}\` when applicable`).join("\n")}
`;
}

/**
 * Build the initial AGENTS.md for a fresh vault: templated content followed
 * by an empty user-prose section. The user edits the user-prose section over
 * time; \`dome doctor --repair\` regenerates the templated section while
 * preserving user-prose byte-for-byte.
 */
export function buildInitialAgentsMd(
  config: VaultConfig,
  pageTypes: PageTypesConfig,
  workflowNames: ReadonlyArray<string>,
): string {
  const templated = buildAgentsMdTemplated(config, pageTypes, workflowNames);
  return `${templated}\n${USER_PROSE_BEGIN}\n\n${USER_PROSE_END}\n`;
}

/**
 * Regenerate AGENTS.md from current config while preserving the user-prose
 * section. Reads the existing user-prose between BEGIN/END markers verbatim
 * and splices it after the new templated content. If the existing file has
 * no delimiters, emits a fresh skeleton.
 */
export function mergeAgentsMd(existing: string, newTemplated: string): string {
  const beginIdx = existing.indexOf(USER_PROSE_BEGIN);
  const endIdx = existing.indexOf(USER_PROSE_END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    return `${newTemplated}\n${USER_PROSE_BEGIN}\n\n${USER_PROSE_END}\n`;
  }
  const userProse = existing.slice(beginIdx + USER_PROSE_BEGIN.length, endIdx);
  return `${newTemplated}\n${USER_PROSE_BEGIN}${userProse}${USER_PROSE_END}\n`;
}
