/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostChatRequestMessagesItemRole = "user" | "assistant" | "system";
export const PostChatRequestMessagesItemRole = {
    User: "user",
    Assistant: "assistant",
    System: "system",
} as const;
