/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface PostChatRequestOptions {
    enhanceWithContext?: boolean;
    maxContextItems?: number;
    includeSourceInfo?: boolean;
    maxTokens?: number;
    temperature?: number;
    modelId?: string;
}
