"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostChatRequestMessagesItemRole = void 0;
exports.PostChatRequestMessagesItemRole = {
    User: "user",
    Assistant: "assistant",
    System: "system",
};
