/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const ReprocessBody: core.serialization.Schema<serializers.ReprocessBody.Raw, DomeApi.ReprocessBody>;
export declare namespace ReprocessBody {
    interface Raw {
        contentId: string;
    }
}
