/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ReprocessBody: core.serialization.Schema<serializers.ReprocessBody.Raw, DomeApi.ReprocessBody> =
    core.serialization.object({
        contentId: core.serialization.string(),
    });

export declare namespace ReprocessBody {
    export interface Raw {
        contentId: string;
    }
}
