/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DomeApi from "../index";
export interface ChatSuccessData {
    response: string;
    /** Supporting sources for the response. */
    sources?: DomeApi.ChatSource[];
}
