/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SearchResultItem {
    id: string;
    title: string;
    summary: string;
    body?: string;
    category: string;
    mimeType: string;
    /** Unix timestamp (milliseconds) */
    createdAt: number;
    /** Unix timestamp (milliseconds) */
    updatedAt?: number;
    score: number;
}
