/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SyncHistoryItem {
    id: string;
    timestamp: Date;
    status: string;
    eventCount?: number;
    summary?: string;
}
