/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DomeApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const BulkReprocessBody: core.serialization.Schema<
    serializers.BulkReprocessBody.Raw,
    DomeApi.BulkReprocessBody
> = core.serialization.object({
    contentIds: core.serialization.list(core.serialization.string()),
});

export declare namespace BulkReprocessBody {
    export interface Raw {
        contentIds: string[];
    }
}
