name = "dome-notify"
main = "src/index.ts"
compatibility_date = "2023-05-18"
inject = "../../wrangler.shared.toml"

# Build configuration
[build]
command = "pnpm build"

[vars]
ENVIRONMENT = "development"
VERSION = "0.1.0"
MAIL_FROM = "notifications@dome.example.com"
MAIL_FROM_NAME = "Dome Notifications"
SLACK_WEBHOOK_URL = ""  # Set this in production

# Environment-specific configurations
[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

