name: Deploy changed Cloudflare workers

on:
  push:
    branches: [ main ]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set.outputs.services }}
      any: ${{ steps.set.outputs.any }}
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ github.token }}
          filters: |
            services:
              - 'services/**'
      - id: set
        shell: bash
        run: |
          files="${{ steps.filter.outputs.services_files }}"
          if [[ -z "$files" ]]; then
            echo "any=false" >>"$GITHUB_OUTPUT"
            echo "services=" >>"$GITHUB_OUTPUT"
            exit 0
          fi
          services=$(echo "$files" | tr ',' '\n' | cut -d/ -f2 | sort -u | tr '\n' ' ')
          echo "Changed services: $services"
          echo "any=true" >>"$GITHUB_OUTPUT"
          echo "services=$services" >>"$GITHUB_OUTPUT"

  deploy:
    needs: detect
    if: needs.detect.outputs.any == 'true'
    strategy:
      matrix:
        service: ${{ fromJson(toJson(split(needs.detect.outputs.services, ' '))) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: {node-version: 18}
      - run: npm install -g wrangler@latest
      - name: Deploy ${{ matrix.service }}
        working-directory: services/${{ matrix.service }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler deploy --env production
