name: Deploy  Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Determine Changed Services
        id: changes
        run: |
          echo "CHANGED_SERVICES<<EOF" >> $GITHUB_OUTPUT
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^services/' \
            | cut -d/ -f2 \
            | sort -u \
            >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Deploy Changed Workers
        if: steps.changes.outputs.CHANGED_SERVICES != ''
        run: |
          for service in ${{ steps.changes.outputs.CHANGED_SERVICES }}; do
            echo "Deploying $service..."
            cd services/$service
            wrangler deploy --env production
            cd -
          done
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
